// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/memory'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/memory"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/memory/memory"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":        reflect.ValueOf(memory.Dial),
		"DialTimeout": reflect.ValueOf(memory.DialTimeout),
		"NewDial":     reflect.ValueOf(memory.NewDial),
		"NewListen":   reflect.ValueOf(memory.NewListen),

		// type definitions
		"Client": reflect.ValueOf((*memory.Client)(nil)),
		"Server": reflect.ValueOf((*memory.Server)(nil)),
	}
}
