// Code generated by 'yaegi extract github.com/injoyai/ios/v2'. DO NOT EDIT.

package lib

import (
	"bufio"
	"github.com/injoyai/ios/v2"
	"go/constant"
	"go/token"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/ios"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bridge":                reflect.ValueOf(ios.Bridge),
		"DefaultBufferSize":     reflect.ValueOf(constant.MakeFromLiteral("1024", token.INT, 0)),
		"Discard":               reflect.ValueOf(ios.Discard),
		"ErrCloseClose":         reflect.ValueOf(&ios.ErrCloseClose).Elem(),
		"ErrClosed":             reflect.ValueOf(&ios.ErrClosed).Elem(),
		"ErrHandClose":          reflect.ValueOf(&ios.ErrHandClose).Elem(),
		"ErrInvalidReadFunc":    reflect.ValueOf(&ios.ErrInvalidReadFunc).Elem(),
		"ErrMaxConnect":         reflect.ValueOf(&ios.ErrMaxConnect).Elem(),
		"ErrNetworkUnusual":     reflect.ValueOf(&ios.ErrNetworkUnusual).Elem(),
		"ErrPortNull":           reflect.ValueOf(&ios.ErrPortNull).Elem(),
		"ErrReadClosed":         reflect.ValueOf(&ios.ErrReadClosed).Elem(),
		"ErrReadTimeout":        reflect.ValueOf(&ios.ErrReadTimeout).Elem(),
		"ErrRemoteClose":        reflect.ValueOf(&ios.ErrRemoteClose).Elem(),
		"ErrRemoteCloseUnusual": reflect.ValueOf(&ios.ErrRemoteCloseUnusual).Elem(),
		"ErrRemoteOff":          reflect.ValueOf(&ios.ErrRemoteOff).Elem(),
		"ErrUnknownReader":      reflect.ValueOf(&ios.ErrUnknownReader).Elem(),
		"ErrUseReadAck":         reflect.ValueOf(&ios.ErrUseReadAck).Elem(),
		"ErrUseReadMessage":     reflect.ValueOf(&ios.ErrUseReadMessage).Elem(),
		"ErrWithConnectTimeout": reflect.ValueOf(&ios.ErrWithConnectTimeout).Elem(),
		"ErrWithContext":        reflect.ValueOf(&ios.ErrWithContext).Elem(),
		"ErrWithTimeout":        reflect.ValueOf(&ios.ErrWithTimeout).Elem(),
		"ErrWriteClosed":        reflect.ValueOf(&ios.ErrWriteClosed).Elem(),
		"ErrWriteTimeout":       reflect.ValueOf(&ios.ErrWriteTimeout).Elem(),
		"MultiCloser":           reflect.ValueOf(ios.MultiCloser),
		"NewAllReader":          reflect.ValueOf(ios.NewAllReader),
		"NewBuffer":             reflect.ValueOf(ios.NewBuffer),
		"NewFRead":              reflect.ValueOf(ios.NewFRead),
		"NewFRead4KB":           reflect.ValueOf(ios.NewFRead4KB),
		"NewFReadB":             reflect.ValueOf(ios.NewFReadB),
		"NewFReadKB":            reflect.ValueOf(ios.NewFReadKB),
		"NewFReadLeast":         reflect.ValueOf(ios.NewFReadLeast),
		"NewMoreWrite":          reflect.ValueOf(ios.NewMoreWrite),
		"NewPiper":              reflect.ValueOf(ios.NewPiper),
		"NewPlanWrite":          reflect.ValueOf(ios.NewPlanWrite),
		"Null":                  reflect.ValueOf(ios.Null),
		"Pipe":                  reflect.ValueOf(ios.Pipe),
		"ReadByte":              reflect.ValueOf(ios.ReadByte),
		"ReadPrefix":            reflect.ValueOf(ios.ReadPrefix),

		// type definitions
		"AReadCloser":        reflect.ValueOf((*ios.AReadCloser)(nil)),
		"AReadFunc":          reflect.ValueOf((*ios.AReadFunc)(nil)),
		"AReadWriteCloser":   reflect.ValueOf((*ios.AReadWriteCloser)(nil)),
		"AReadWriter":        reflect.ValueOf((*ios.AReadWriter)(nil)),
		"AReader":            reflect.ValueOf((*ios.AReader)(nil)),
		"Ack":                reflect.ValueOf((*ios.Ack)(nil)),
		"Acker":              reflect.ValueOf((*ios.Acker)(nil)),
		"AllRead":            reflect.ValueOf((*ios.AllRead)(nil)),
		"AllReadWriteCloser": reflect.ValueOf((*ios.AllReadWriteCloser)(nil)),
		"AllReader":          reflect.ValueOf((*ios.AllReader)(nil)),
		"AnyWriter":          reflect.ValueOf((*ios.AnyWriter)(nil)),
		"BReadCloser":        reflect.ValueOf((*ios.BReadCloser)(nil)),
		"BReadFunc":          reflect.ValueOf((*ios.BReadFunc)(nil)),
		"BReadWriteCloser":   reflect.ValueOf((*ios.BReadWriteCloser)(nil)),
		"BReadWriter":        reflect.ValueOf((*ios.BReadWriter)(nil)),
		"BReader":            reflect.ValueOf((*ios.BReader)(nil)),
		"Base64Writer":       reflect.ValueOf((*ios.Base64Writer)(nil)),
		"Buffer":             reflect.ValueOf((*ios.Buffer)(nil)),
		"Bytes":              reflect.ValueOf((*ios.Bytes)(nil)),
		"ChanWriter":         reflect.ValueOf((*ios.ChanWriter)(nil)),
		"CloseFunc":          reflect.ValueOf((*ios.CloseFunc)(nil)),
		"Closer":             reflect.ValueOf((*ios.Closer)(nil)),
		"DialFunc":           reflect.ValueOf((*ios.DialFunc)(nil)),
		"FReadFunc":          reflect.ValueOf((*ios.FReadFunc)(nil)),
		"FReader":            reflect.ValueOf((*ios.FReader)(nil)),
		"HEXWriter":          reflect.ValueOf((*ios.HEXWriter)(nil)),
		"JsonWriter":         reflect.ValueOf((*ios.JsonWriter)(nil)),
		"ListenFunc":         reflect.ValueOf((*ios.ListenFunc)(nil)),
		"Listener":           reflect.ValueOf((*ios.Listener)(nil)),
		"MoreWrite":          reflect.ValueOf((*ios.MoreWrite)(nil)),
		"MoreWriter":         reflect.ValueOf((*ios.MoreWriter)(nil)),
		"Piper":              reflect.ValueOf((*ios.Piper)(nil)),
		"Plan":               reflect.ValueOf((*ios.Plan)(nil)),
		"PlanWrite":          reflect.ValueOf((*ios.PlanWrite)(nil)),
		"ReadCloser":         reflect.ValueOf((*ios.ReadCloser)(nil)),
		"ReadFunc":           reflect.ValueOf((*ios.ReadFunc)(nil)),
		"ReadWriteCloser":    reflect.ValueOf((*ios.ReadWriteCloser)(nil)),
		"Reader":             reflect.ValueOf((*ios.Reader)(nil)),
		"SetReadDeadliner":   reflect.ValueOf((*ios.SetReadDeadliner)(nil)),
		"WriteFunc":          reflect.ValueOf((*ios.WriteFunc)(nil)),

		// interface wrapper definitions
		"_AReadCloser":        reflect.ValueOf((*_github_com_injoyai_ios_v2_AReadCloser)(nil)),
		"_AReadWriteCloser":   reflect.ValueOf((*_github_com_injoyai_ios_v2_AReadWriteCloser)(nil)),
		"_AReadWriter":        reflect.ValueOf((*_github_com_injoyai_ios_v2_AReadWriter)(nil)),
		"_AReader":            reflect.ValueOf((*_github_com_injoyai_ios_v2_AReader)(nil)),
		"_Acker":              reflect.ValueOf((*_github_com_injoyai_ios_v2_Acker)(nil)),
		"_AllReadWriteCloser": reflect.ValueOf((*_github_com_injoyai_ios_v2_AllReadWriteCloser)(nil)),
		"_AllReader":          reflect.ValueOf((*_github_com_injoyai_ios_v2_AllReader)(nil)),
		"_AnyWriter":          reflect.ValueOf((*_github_com_injoyai_ios_v2_AnyWriter)(nil)),
		"_BReadCloser":        reflect.ValueOf((*_github_com_injoyai_ios_v2_BReadCloser)(nil)),
		"_BReadWriteCloser":   reflect.ValueOf((*_github_com_injoyai_ios_v2_BReadWriteCloser)(nil)),
		"_BReadWriter":        reflect.ValueOf((*_github_com_injoyai_ios_v2_BReadWriter)(nil)),
		"_BReader":            reflect.ValueOf((*_github_com_injoyai_ios_v2_BReader)(nil)),
		"_Base64Writer":       reflect.ValueOf((*_github_com_injoyai_ios_v2_Base64Writer)(nil)),
		"_ChanWriter":         reflect.ValueOf((*_github_com_injoyai_ios_v2_ChanWriter)(nil)),
		"_Closer":             reflect.ValueOf((*_github_com_injoyai_ios_v2_Closer)(nil)),
		"_FReader":            reflect.ValueOf((*_github_com_injoyai_ios_v2_FReader)(nil)),
		"_HEXWriter":          reflect.ValueOf((*_github_com_injoyai_ios_v2_HEXWriter)(nil)),
		"_JsonWriter":         reflect.ValueOf((*_github_com_injoyai_ios_v2_JsonWriter)(nil)),
		"_Listener":           reflect.ValueOf((*_github_com_injoyai_ios_v2_Listener)(nil)),
		"_MoreWriter":         reflect.ValueOf((*_github_com_injoyai_ios_v2_MoreWriter)(nil)),
		"_ReadCloser":         reflect.ValueOf((*_github_com_injoyai_ios_v2_ReadCloser)(nil)),
		"_ReadWriteCloser":    reflect.ValueOf((*_github_com_injoyai_ios_v2_ReadWriteCloser)(nil)),
		"_Reader":             reflect.ValueOf((*_github_com_injoyai_ios_v2_Reader)(nil)),
		"_SetReadDeadliner":   reflect.ValueOf((*_github_com_injoyai_ios_v2_SetReadDeadliner)(nil)),
	}
}

// _github_com_injoyai_ios_v2_AReadCloser is an interface wrapper for AReadCloser type
type _github_com_injoyai_ios_v2_AReadCloser struct {
	IValue   interface{}
	WClose   func() error
	WReadAck func() (ios.Acker, error)
}

func (W _github_com_injoyai_ios_v2_AReadCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_AReadCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}

// _github_com_injoyai_ios_v2_AReadWriteCloser is an interface wrapper for AReadWriteCloser type
type _github_com_injoyai_ios_v2_AReadWriteCloser struct {
	IValue   interface{}
	WClose   func() error
	WReadAck func() (ios.Acker, error)
	WWrite   func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_AReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_AReadWriteCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_v2_AReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_AReadWriter is an interface wrapper for AReadWriter type
type _github_com_injoyai_ios_v2_AReadWriter struct {
	IValue   interface{}
	WReadAck func() (ios.Acker, error)
	WWrite   func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_AReadWriter) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_v2_AReadWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_AReader is an interface wrapper for AReader type
type _github_com_injoyai_ios_v2_AReader struct {
	IValue   interface{}
	WReadAck func() (ios.Acker, error)
}

func (W _github_com_injoyai_ios_v2_AReader) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}

// _github_com_injoyai_ios_v2_Acker is an interface wrapper for Acker type
type _github_com_injoyai_ios_v2_Acker struct {
	IValue interface{}
	WAck   func() error
	WBytes func() []byte
}

func (W _github_com_injoyai_ios_v2_Acker) Ack() error {
	return W.WAck()
}
func (W _github_com_injoyai_ios_v2_Acker) Bytes() []byte {
	return W.WBytes()
}

// _github_com_injoyai_ios_v2_AllReadWriteCloser is an interface wrapper for AllReadWriteCloser type
type _github_com_injoyai_ios_v2_AllReadWriteCloser struct {
	IValue     interface{}
	WClose     func() error
	WRead      func(p []byte) (n int, err error)
	WReadAck   func() (ios.Acker, error)
	WReadBytes func() ([]byte, error)
	WWrite     func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_AllReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_AllReadWriteCloser) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_v2_AllReadWriteCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_v2_AllReadWriteCloser) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}
func (W _github_com_injoyai_ios_v2_AllReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_AllReader is an interface wrapper for AllReader type
type _github_com_injoyai_ios_v2_AllReader struct {
	IValue     interface{}
	WRead      func(p []byte) (n int, err error)
	WReadAck   func() (ios.Acker, error)
	WReadBytes func() ([]byte, error)
}

func (W _github_com_injoyai_ios_v2_AllReader) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_v2_AllReader) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_v2_AllReader) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}

// _github_com_injoyai_ios_v2_AnyWriter is an interface wrapper for AnyWriter type
type _github_com_injoyai_ios_v2_AnyWriter struct {
	IValue    interface{}
	WWriteAny func(a any) error
}

func (W _github_com_injoyai_ios_v2_AnyWriter) WriteAny(a any) error {
	return W.WWriteAny(a)
}

// _github_com_injoyai_ios_v2_BReadCloser is an interface wrapper for BReadCloser type
type _github_com_injoyai_ios_v2_BReadCloser struct {
	IValue     interface{}
	WClose     func() error
	WReadBytes func() ([]byte, error)
}

func (W _github_com_injoyai_ios_v2_BReadCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_BReadCloser) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}

// _github_com_injoyai_ios_v2_BReadWriteCloser is an interface wrapper for BReadWriteCloser type
type _github_com_injoyai_ios_v2_BReadWriteCloser struct {
	IValue     interface{}
	WClose     func() error
	WReadBytes func() ([]byte, error)
	WWrite     func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_BReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_BReadWriteCloser) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}
func (W _github_com_injoyai_ios_v2_BReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_BReadWriter is an interface wrapper for BReadWriter type
type _github_com_injoyai_ios_v2_BReadWriter struct {
	IValue     interface{}
	WReadBytes func() ([]byte, error)
	WWrite     func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_BReadWriter) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}
func (W _github_com_injoyai_ios_v2_BReadWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_BReader is an interface wrapper for BReader type
type _github_com_injoyai_ios_v2_BReader struct {
	IValue     interface{}
	WReadBytes func() ([]byte, error)
}

func (W _github_com_injoyai_ios_v2_BReader) ReadBytes() ([]byte, error) {
	return W.WReadBytes()
}

// _github_com_injoyai_ios_v2_Base64Writer is an interface wrapper for Base64Writer type
type _github_com_injoyai_ios_v2_Base64Writer struct {
	IValue       interface{}
	WWriteBase64 func(s string) error
}

func (W _github_com_injoyai_ios_v2_Base64Writer) WriteBase64(s string) error {
	return W.WWriteBase64(s)
}

// _github_com_injoyai_ios_v2_ChanWriter is an interface wrapper for ChanWriter type
type _github_com_injoyai_ios_v2_ChanWriter struct {
	IValue     interface{}
	WWriteChan func(c chan any) error
}

func (W _github_com_injoyai_ios_v2_ChanWriter) WriteChan(c chan any) error {
	return W.WWriteChan(c)
}

// _github_com_injoyai_ios_v2_Closer is an interface wrapper for Closer type
type _github_com_injoyai_ios_v2_Closer struct {
	IValue  interface{}
	WClose  func() error
	WClosed func() bool
}

func (W _github_com_injoyai_ios_v2_Closer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_Closer) Closed() bool {
	return W.WClosed()
}

// _github_com_injoyai_ios_v2_FReader is an interface wrapper for FReader type
type _github_com_injoyai_ios_v2_FReader struct {
	IValue    interface{}
	WReadFrom func(r *bufio.Reader) ([]byte, error)
}

func (W _github_com_injoyai_ios_v2_FReader) ReadFrom(r *bufio.Reader) ([]byte, error) {
	return W.WReadFrom(r)
}

// _github_com_injoyai_ios_v2_HEXWriter is an interface wrapper for HEXWriter type
type _github_com_injoyai_ios_v2_HEXWriter struct {
	IValue    interface{}
	WWriteHEX func(s string) error
}

func (W _github_com_injoyai_ios_v2_HEXWriter) WriteHEX(s string) error {
	return W.WWriteHEX(s)
}

// _github_com_injoyai_ios_v2_JsonWriter is an interface wrapper for JsonWriter type
type _github_com_injoyai_ios_v2_JsonWriter struct {
	IValue     interface{}
	WWriteJson func(a any) error
}

func (W _github_com_injoyai_ios_v2_JsonWriter) WriteJson(a any) error {
	return W.WWriteJson(a)
}

// _github_com_injoyai_ios_v2_Listener is an interface wrapper for Listener type
type _github_com_injoyai_ios_v2_Listener struct {
	IValue  interface{}
	WAccept func() (ios.ReadWriteCloser, string, error)
	WAddr   func() string
	WClose  func() error
}

func (W _github_com_injoyai_ios_v2_Listener) Accept() (ios.ReadWriteCloser, string, error) {
	return W.WAccept()
}
func (W _github_com_injoyai_ios_v2_Listener) Addr() string {
	return W.WAddr()
}
func (W _github_com_injoyai_ios_v2_Listener) Close() error {
	return W.WClose()
}

// _github_com_injoyai_ios_v2_MoreWriter is an interface wrapper for MoreWriter type
type _github_com_injoyai_ios_v2_MoreWriter struct {
	IValue       interface{}
	WWrite       func(p []byte) (n int, err error)
	WWriteAny    func(a any) error
	WWriteBase64 func(s string) error
	WWriteByte   func(c byte) error
	WWriteChan   func(c chan any) error
	WWriteHEX    func(s string) error
	WWriteJson   func(a any) error
	WWriteString func(s string) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_MoreWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteAny(a any) error {
	return W.WWriteAny(a)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteBase64(s string) error {
	return W.WWriteBase64(s)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteByte(c byte) error {
	return W.WWriteByte(c)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteChan(c chan any) error {
	return W.WWriteChan(c)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteHEX(s string) error {
	return W.WWriteHEX(s)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteJson(a any) error {
	return W.WWriteJson(a)
}
func (W _github_com_injoyai_ios_v2_MoreWriter) WriteString(s string) (n int, err error) {
	return W.WWriteString(s)
}

// _github_com_injoyai_ios_v2_ReadCloser is an interface wrapper for ReadCloser type
type _github_com_injoyai_ios_v2_ReadCloser struct {
	IValue interface{}
	WClose func() error
}

func (W _github_com_injoyai_ios_v2_ReadCloser) Close() error {
	return W.WClose()
}

// _github_com_injoyai_ios_v2_ReadWriteCloser is an interface wrapper for ReadWriteCloser type
type _github_com_injoyai_ios_v2_ReadWriteCloser struct {
	IValue interface{}
	WClose func() error
	WWrite func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_ReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_ReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_v2_Reader is an interface wrapper for Reader type
type _github_com_injoyai_ios_v2_Reader struct {
	IValue interface{}
}

// _github_com_injoyai_ios_v2_SetReadDeadliner is an interface wrapper for SetReadDeadliner type
type _github_com_injoyai_ios_v2_SetReadDeadliner struct {
	IValue           interface{}
	WSetReadDeadline func(t time.Time) error
}

func (W _github_com_injoyai_ios_v2_SetReadDeadliner) SetReadDeadline(t time.Time) error {
	return W.WSetReadDeadline(t)
}
