// Code generated by 'yaegi extract github.com/injoyai/frame/middle/swagger'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/frame/middle/swagger"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/frame/middle/swagger/swagger"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default":   reflect.ValueOf(&swagger.Default).Elem(),
		"DefaultUI": reflect.ValueOf(&swagger.DefaultUI).Elem(),

		// type definitions
		"Swagger": reflect.ValueOf((*swagger.Swagger)(nil)),
	}
}
