// Code generated by 'yaegi extract github.com/injoyai/ios/v2/client'. DO NOT EDIT.

package lib

import (
	"bufio"
	"github.com/injoyai/ios/v2/client"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/client/client"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultReaderPool":        reflect.ValueOf(&client.DefaultReaderPool).Elem(),
		"Dial":                     reflect.ValueOf(client.Dial),
		"DialContext":              reflect.ValueOf(client.DialContext),
		"New":                      reflect.ValueOf(client.New),
		"NewDealMessageWithChan":   reflect.ValueOf(client.NewDealMessageWithChan),
		"NewDealMessageWithWriter": reflect.ValueOf(client.NewDealMessageWithWriter),
		"NewDisconnectAfter":       reflect.ValueOf(client.NewDisconnectAfter),
		"NewPool":                  reflect.ValueOf(client.NewPool),
		"NewReconnectInterval":     reflect.ValueOf(client.NewReconnectInterval),
		"NewReconnectRetreat":      reflect.ValueOf(client.NewReconnectRetreat),
		"NewWriteRetry":            reflect.ValueOf(client.NewWriteRetry),
		"NewWriteSafe":             reflect.ValueOf(client.NewWriteSafe),
		"Redial":                   reflect.ValueOf(client.Redial),
		"RedialContext":            reflect.ValueOf(client.RedialContext),
		"Run":                      reflect.ValueOf(client.Run),
		"RunContext":               reflect.ValueOf(client.RunContext),
		"WithConnect":              reflect.ValueOf(client.WithConnect),
		"WithDealMessage":          reflect.ValueOf(client.WithDealMessage),
		"WithDebug":                reflect.ValueOf(client.WithDebug),
		"WithDisconnect":           reflect.ValueOf(client.WithDisconnect),
		"WithFrame":                reflect.ValueOf(client.WithFrame),
		"WithHEX":                  reflect.ValueOf(client.WithHEX),
		"WithLevel":                reflect.ValueOf(client.WithLevel),
		"WithReadFrom":             reflect.ValueOf(client.WithReadFrom),
		"WithRedial":               reflect.ValueOf(client.WithRedial),
		"WithUTF8":                 reflect.ValueOf(client.WithUTF8),
		"WithWriteRetry":           reflect.ValueOf(client.WithWriteRetry),
		"WithWriteSafe":            reflect.ValueOf(client.WithWriteSafe),
		"WithWriteWith":            reflect.ValueOf(client.WithWriteWith),

		// type definitions
		"Client": reflect.ValueOf((*client.Client)(nil)),
		"Frame":  reflect.ValueOf((*client.Frame)(nil)),
		"Info":   reflect.ValueOf((*client.Info)(nil)),
		"Option": reflect.ValueOf((*client.Option)(nil)),
		"Pool":   reflect.ValueOf((*client.Pool)(nil)),

		// interface wrapper definitions
		"_Frame": reflect.ValueOf((*_github_com_injoyai_ios_v2_client_Frame)(nil)),
	}
}

// _github_com_injoyai_ios_v2_client_Frame is an interface wrapper for Frame type
type _github_com_injoyai_ios_v2_client_Frame struct {
	IValue     interface{}
	WReadFrom  func(r *bufio.Reader) ([]byte, error)
	WWriteWith func(bs []byte) ([]byte, error)
}

func (W _github_com_injoyai_ios_v2_client_Frame) ReadFrom(r *bufio.Reader) ([]byte, error) {
	return W.WReadFrom(r)
}
func (W _github_com_injoyai_ios_v2_client_Frame) WriteWith(bs []byte) ([]byte, error) {
	return W.WWriteWith(bs)
}
