// Code generated by 'yaegi extract github.com/injoyai/ios/v2/client/redial'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/client/redial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/client/redial/redial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Memory":       reflect.ValueOf(redial.Memory),
		"Run":          reflect.ValueOf(redial.Run),
		"RunMemory":    reflect.ValueOf(redial.RunMemory),
		"RunTCP":       reflect.ValueOf(redial.RunTCP),
		"RunUDP":       reflect.ValueOf(redial.RunUDP),
		"RunUnix":      reflect.ValueOf(redial.RunUnix),
		"RunWebsocket": reflect.ValueOf(redial.RunWebsocket),
		"TCP":          reflect.ValueOf(redial.TCP),
		"UDP":          reflect.ValueOf(redial.UDP),
		"Unix":         reflect.ValueOf(redial.Unix),
		"Websocket":    reflect.ValueOf(redial.Websocket),
		"With":         reflect.ValueOf(redial.With),
	}
}
