// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/unix'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/unix"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/unix/unix"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewDial":   reflect.ValueOf(unix.NewDial),
		"NewListen": reflect.ValueOf(unix.NewListen),

		// type definitions
		"Server": reflect.ValueOf((*unix.Server)(nil)),
	}
}
