// Code generated by 'yaegi extract github.com/injoyai/logs'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/logs"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/logs/logs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddWriter":               reflect.ValueOf(logs.AddWriter),
		"Debug":                   reflect.ValueOf(logs.Debug),
		"Debugf":                  reflect.ValueOf(logs.Debugf),
		"DefaultDebug":            reflect.ValueOf(&logs.DefaultDebug).Elem(),
		"DefaultErr":              reflect.ValueOf(&logs.DefaultErr).Elem(),
		"DefaultFormatter":        reflect.ValueOf(&logs.DefaultFormatter).Elem(),
		"DefaultInfo":             reflect.ValueOf(&logs.DefaultInfo).Elem(),
		"DefaultRead":             reflect.ValueOf(&logs.DefaultRead).Elem(),
		"DefaultTrace":            reflect.ValueOf(&logs.DefaultTrace).Elem(),
		"DefaultWarn":             reflect.ValueOf(&logs.DefaultWarn).Elem(),
		"DefaultWrite":            reflect.ValueOf(&logs.DefaultWrite).Elem(),
		"DialTCP":                 reflect.ValueOf(logs.DialTCP),
		"Err":                     reflect.ValueOf(logs.Err),
		"Errf":                    reflect.ValueOf(logs.Errf),
		"Error":                   reflect.ValueOf(logs.Error),
		"Errorf":                  reflect.ValueOf(logs.Errorf),
		"FDefault":                reflect.ValueOf(&logs.FDefault).Elem(),
		"FJson":                   reflect.ValueOf(&logs.FJson).Elem(),
		"FTime":                   reflect.ValueOf(&logs.FTime).Elem(),
		"Fatal":                   reflect.ValueOf(logs.Fatal),
		"Fatalf":                  reflect.ValueOf(logs.Fatalf),
		"Info":                    reflect.ValueOf(logs.Info),
		"Infof":                   reflect.ValueOf(logs.Infof),
		"LevelAll":                reflect.ValueOf(logs.LevelAll),
		"LevelDebug":              reflect.ValueOf(logs.LevelDebug),
		"LevelError":              reflect.ValueOf(logs.LevelError),
		"LevelInfo":               reflect.ValueOf(logs.LevelInfo),
		"LevelNone":               reflect.ValueOf(logs.LevelNone),
		"LevelRead":               reflect.ValueOf(logs.LevelRead),
		"LevelTrace":              reflect.ValueOf(logs.LevelTrace),
		"LevelWarn":               reflect.ValueOf(logs.LevelWarn),
		"LevelWrite":              reflect.ValueOf(logs.LevelWrite),
		"New":                     reflect.ValueOf(logs.New),
		"NewEntity":               reflect.ValueOf(logs.NewEntity),
		"NewFile":                 reflect.ValueOf(logs.NewFile),
		"NewFilter":               reflect.ValueOf(logs.NewFilter),
		"NewHTTPClient":           reflect.ValueOf(logs.NewHTTPClient),
		"NewTCPClient":            reflect.ValueOf(logs.NewTCPClient),
		"NewTCPServer":            reflect.ValueOf(logs.NewTCPServer),
		"NewWriteColor":           reflect.ValueOf(logs.NewWriteColor),
		"Panic":                   reflect.ValueOf(logs.Panic),
		"PanicErr":                reflect.ValueOf(logs.PanicErr),
		"Panicf":                  reflect.ValueOf(logs.Panicf),
		"ParseLevel":              reflect.ValueOf(logs.ParseLevel),
		"PrintErr":                reflect.ValueOf(logs.PrintErr),
		"Read":                    reflect.ValueOf(logs.Read),
		"Readf":                   reflect.ValueOf(logs.Readf),
		"SetCaller":               reflect.ValueOf(logs.SetCaller),
		"SetFormatter":            reflect.ValueOf(logs.SetFormatter),
		"SetFormatterWithDefault": reflect.ValueOf(logs.SetFormatterWithDefault),
		"SetFormatterWithTime":    reflect.ValueOf(logs.SetFormatterWithTime),
		"SetLevel":                reflect.ValueOf(logs.SetLevel),
		"SetLevelWithAll":         reflect.ValueOf(logs.SetLevelWithAll),
		"SetShowColor":            reflect.ValueOf(logs.SetShowColor),
		"SetWriter":               reflect.ValueOf(logs.SetWriter),
		"Spend":                   reflect.ValueOf(logs.Spend),
		"Stdout":                  reflect.ValueOf(&logs.Stdout).Elem(),
		"TimeFormatter":           reflect.ValueOf(&logs.TimeFormatter).Elem(),
		"Trace":                   reflect.ValueOf(logs.Trace),
		"Tracef":                  reflect.ValueOf(logs.Tracef),
		"Trunk":                   reflect.ValueOf(&logs.Trunk).Elem(),
		"Warn":                    reflect.ValueOf(logs.Warn),
		"Warnf":                   reflect.ValueOf(logs.Warnf),
		"Write":                   reflect.ValueOf(logs.Write),
		"WriteToHTTPServer":       reflect.ValueOf(logs.WriteToHTTPServer),
		"WriteToTCPClient":        reflect.ValueOf(logs.WriteToTCPClient),
		"WriteToTCPServer":        reflect.ValueOf(logs.WriteToTCPServer),
		"Writef":                  reflect.ValueOf(logs.Writef),

		// type definitions
		"Chan":       reflect.ValueOf((*logs.Chan)(nil)),
		"Entity":     reflect.ValueOf((*logs.Entity)(nil)),
		"File":       reflect.ValueOf((*logs.File)(nil)),
		"Filter":     reflect.ValueOf((*logs.Filter)(nil)),
		"FormatFunc": reflect.ValueOf((*logs.FormatFunc)(nil)),
		"IFormatter": reflect.ValueOf((*logs.IFormatter)(nil)),
		"Level":      reflect.ValueOf((*logs.Level)(nil)),
		"Logger":     reflect.ValueOf((*logs.Logger)(nil)),

		// interface wrapper definitions
		"_IFormatter": reflect.ValueOf((*_github_com_injoyai_logs_IFormatter)(nil)),
	}
}

// _github_com_injoyai_logs_IFormatter is an interface wrapper for IFormatter type
type _github_com_injoyai_logs_IFormatter struct {
	IValue     interface{}
	WFormatter func(e *logs.Entity, msg string) string
}

func (W _github_com_injoyai_logs_IFormatter) Formatter(e *logs.Entity, msg string) string {
	return W.WFormatter(e, msg)
}
