// Code generated by 'yaegi extract github.com/injoyai/frame/middle/easy_user'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/frame/middle/easy_user"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/frame/middle/easy_user/easy_user"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrAuthFail": reflect.ValueOf(&easy_user.ErrAuthFail).Elem(),
		"ErrInput":    reflect.ValueOf(&easy_user.ErrInput).Elem(),
		"ErrNotFind":  reflect.ValueOf(&easy_user.ErrNotFind).Elem(),
		"NewManage":   reflect.ValueOf(easy_user.NewManage),

		// type definitions
		"Config":              reflect.ValueOf((*easy_user.Config)(nil)),
		"EditInfoRequest":     reflect.ValueOf((*easy_user.EditInfoRequest)(nil)),
		"EditPasswordRequest": reflect.ValueOf((*easy_user.EditPasswordRequest)(nil)),
		"LoginInfo":           reflect.ValueOf((*easy_user.LoginInfo)(nil)),
		"LoginRequest":        reflect.ValueOf((*easy_user.LoginRequest)(nil)),
		"Manage":              reflect.ValueOf((*easy_user.Manage)(nil)),
		"User":                reflect.ValueOf((*easy_user.User)(nil)),
		"UserCreateRequest":   reflect.ValueOf((*easy_user.UserCreateRequest)(nil)),
	}
}
