// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/ssh'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/ssh"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/ssh/ssh"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":    reflect.ValueOf(ssh.Dial),
		"NewDial": reflect.ValueOf(ssh.NewDial),

		// type definitions
		"Client": reflect.ValueOf((*ssh.Client)(nil)),
		"Config": reflect.ValueOf((*ssh.Config)(nil)),
	}
}
