// Code generated by 'yaegi extract github.com/injoyai/base/crypt/des'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/des"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/des/des"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DecryptECB":       reflect.ValueOf(des.DecryptECB),
		"DecryptECBBase64": reflect.ValueOf(des.DecryptECBBase64),
		"DecryptECBBytes":  reflect.ValueOf(des.DecryptECBBytes),
		"DecryptECBHEX":    reflect.ValueOf(des.DecryptECBHEX),
		"DecryptECBString": reflect.ValueOf(des.DecryptECBString),
		"EncryptECB":       reflect.ValueOf(des.EncryptECB),
		"EncryptECBBase64": reflect.ValueOf(des.EncryptECBBase64),
		"EncryptECBBytes":  reflect.ValueOf(des.EncryptECBBytes),
		"EncryptECBHEX":    reflect.ValueOf(des.EncryptECBHEX),
		"EncryptECBString": reflect.ValueOf(des.EncryptECBString),
	}
}
