// Code generated by 'yaegi extract github.com/injoyai/conv/codec'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/codec"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default": reflect.ValueOf(&codec.Default).Elem(),
		"Get":     reflect.ValueOf(codec.Get),
		"Ini":     reflect.ValueOf(&codec.Ini).Elem(),
		"Json":    reflect.ValueOf(&codec.Json).Elem(),
		"Toml":    reflect.ValueOf(&codec.Toml).Elem(),
		"Yaml":    reflect.ValueOf(&codec.Yaml).Elem(),

		// type definitions
		"Interface": reflect.ValueOf((*codec.Interface)(nil)),

		// interface wrapper definitions
		"_Interface": reflect.ValueOf((*_github_com_injoyai_conv_codec_Interface)(nil)),
	}
}

// _github_com_injoyai_conv_codec_Interface is an interface wrapper for Interface type
type _github_com_injoyai_conv_codec_Interface struct {
	IValue     interface{}
	WMarshal   func(v any) ([]byte, error)
	WUnmarshal func(data []byte, v any) error
}

func (W _github_com_injoyai_conv_codec_Interface) Marshal(v any) ([]byte, error) {
	return W.WMarshal(v)
}
func (W _github_com_injoyai_conv_codec_Interface) Unmarshal(data []byte, v any) error {
	return W.WUnmarshal(data, v)
}
