// Code generated by 'yaegi extract github.com/injoyai/base/safe'. DO NOT EDIT.

package lib

import (
	"context"
	"github.com/injoyai/base/safe"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/safe/safe"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Index":                 reflect.ValueOf(safe.Index),
		"NewCloser":             reflect.ValueOf(safe.NewCloser),
		"NewCloserErr":          reflect.ValueOf(safe.NewCloserErr),
		"NewGoroute":            reflect.ValueOf(safe.NewGoroute),
		"NewGorouteWithContext": reflect.ValueOf(safe.NewGorouteWithContext),
		"NewInt32":              reflect.ValueOf(safe.NewInt32),
		"NewInt64":              reflect.ValueOf(safe.NewInt64),
		"NewOneRun":             reflect.ValueOf(safe.NewOneRun),
		"NewRerun":              reflect.ValueOf(safe.NewRerun),
		"NewRunner":             reflect.ValueOf(safe.NewRunner),
		"NewRunner2":            reflect.ValueOf(safe.NewRunner2),
		"NewRunnerWithContext":  reflect.ValueOf(safe.NewRunnerWithContext),
		"NewUint32":             reflect.ValueOf(safe.NewUint32),
		"NewUint64":             reflect.ValueOf(safe.NewUint64),
		"NewUse":                reflect.ValueOf(safe.NewUse),
		"Recover":               reflect.ValueOf(safe.Recover),
		"RecoverFunc":           reflect.ValueOf(safe.RecoverFunc),
		"Retry":                 reflect.ValueOf(safe.Retry),
		"Try":                   reflect.ValueOf(safe.Try),

		// type definitions
		"Bool":    reflect.ValueOf((*safe.Bool)(nil)),
		"Closer":  reflect.ValueOf((*safe.Closer)(nil)),
		"Dialer":  reflect.ValueOf((*safe.Dialer)(nil)),
		"Goroute": reflect.ValueOf((*safe.Goroute)(nil)),
		"Int32":   reflect.ValueOf((*safe.Int32)(nil)),
		"Int64":   reflect.ValueOf((*safe.Int64)(nil)),
		"Once":    reflect.ValueOf((*safe.Once)(nil)),
		"OneRun":  reflect.ValueOf((*safe.OneRun)(nil)),
		"Rerun":   reflect.ValueOf((*safe.Rerun)(nil)),
		"Runner":  reflect.ValueOf((*safe.Runner)(nil)),
		"Runner2": reflect.ValueOf((*safe.Runner2)(nil)),
		"Uint32":  reflect.ValueOf((*safe.Uint32)(nil)),
		"Uint64":  reflect.ValueOf((*safe.Uint64)(nil)),
		"Use":     reflect.ValueOf((*safe.Use)(nil)),
		"Value":   reflect.ValueOf((*safe.Value)(nil)),

		// interface wrapper definitions
		"_Dialer": reflect.ValueOf((*_github_com_injoyai_base_safe_Dialer)(nil)),
		"_OneRun": reflect.ValueOf((*_github_com_injoyai_base_safe_OneRun)(nil)),
	}
}

// _github_com_injoyai_base_safe_Dialer is an interface wrapper for Dialer type
type _github_com_injoyai_base_safe_Dialer struct {
	IValue interface{}
	WClose func() error
	WDial  func(ctx context.Context) error
	WRun   func(ctx context.Context) error
}

func (W _github_com_injoyai_base_safe_Dialer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_base_safe_Dialer) Dial(ctx context.Context) error {
	return W.WDial(ctx)
}
func (W _github_com_injoyai_base_safe_Dialer) Run(ctx context.Context) error {
	return W.WRun(ctx)
}

// _github_com_injoyai_base_safe_OneRun is an interface wrapper for OneRun type
type _github_com_injoyai_base_safe_OneRun struct {
	IValue      interface{}
	WClose      func() error
	WRun        func(ctx context.Context) error
	WRunning    func() bool
	WSetHandler func(fn func(ctx context.Context) error)
}

func (W _github_com_injoyai_base_safe_OneRun) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_base_safe_OneRun) Run(ctx context.Context) error {
	return W.WRun(ctx)
}
func (W _github_com_injoyai_base_safe_OneRun) Running() bool {
	return W.WRunning()
}
func (W _github_com_injoyai_base_safe_OneRun) SetHandler(fn func(ctx context.Context) error) {
	W.WSetHandler(fn)
}
