// Code generated by 'yaegi extract github.com/injoyai/frame/middle/in'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/maps"
	"github.com/injoyai/frame/middle/in"
	"io"
	"net/http"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/frame/middle/in/in"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckErr":           reflect.ValueOf(in.CheckErr),
		"Custom":             reflect.ValueOf(in.Custom),
		"Custom200":          reflect.ValueOf(in.Custom200),
		"DefaultClient":      reflect.ValueOf(&in.DefaultClient).Elem(),
		"DelCache":           reflect.ValueOf(in.DelCache),
		"Err":                reflect.ValueOf(in.Err),
		"Fail":               reflect.ValueOf(in.Fail),
		"FileBytes":          reflect.ValueOf(in.FileBytes),
		"FileLocal":          reflect.ValueOf(in.FileLocal),
		"FileReader":         reflect.ValueOf(in.FileReader),
		"Forbidden":          reflect.ValueOf(in.Forbidden),
		"GetBodyMap":         reflect.ValueOf(in.GetBodyMap),
		"GetBodyVar":         reflect.ValueOf(in.GetBodyVar),
		"GetHeaderVar":       reflect.ValueOf(in.GetHeaderVar),
		"GetPageNum":         reflect.ValueOf(in.GetPageNum),
		"GetPageSize":        reflect.ValueOf(in.GetPageSize),
		"GetQueryVar":        reflect.ValueOf(in.GetQueryVar),
		"GetVar":             reflect.ValueOf(in.GetVar),
		"Html":               reflect.ValueOf(in.Html),
		"Html200":            reflect.ValueOf(in.Html200),
		"HtmlLocal":          reflect.ValueOf(in.HtmlLocal),
		"HtmlReader":         reflect.ValueOf(in.HtmlReader),
		"Json":               reflect.ValueOf(in.Json),
		"Json200":            reflect.ValueOf(in.Json200),
		"Json400":            reflect.ValueOf(in.Json400),
		"Json401":            reflect.ValueOf(in.Json401),
		"Json403":            reflect.ValueOf(in.Json403),
		"Json404":            reflect.ValueOf(in.Json404),
		"Json415":            reflect.ValueOf(in.Json415),
		"Json500":            reflect.ValueOf(in.Json500),
		"New":                reflect.ValueOf(in.New),
		"NewRequest":         reflect.ValueOf(in.NewRequest),
		"NewWriter":          reflect.ValueOf(in.NewWriter),
		"Proxy":              reflect.ValueOf(in.Proxy),
		"Reader":             reflect.ValueOf(in.Reader),
		"Reader200":          reflect.ValueOf(in.Reader200),
		"Recover":            reflect.ValueOf(in.Recover),
		"RecoverFunc":        reflect.ValueOf(in.RecoverFunc),
		"RecoverWriter":      reflect.ValueOf(in.RecoverWriter),
		"Redirect301":        reflect.ValueOf(in.Redirect301),
		"Redirect302":        reflect.ValueOf(in.Redirect302),
		"Redirect307":        reflect.ValueOf(in.Redirect307),
		"Redirect308":        reflect.ValueOf(in.Redirect308),
		"SetCache":           reflect.ValueOf(in.SetCache),
		"SetCacheByHandler":  reflect.ValueOf(in.SetCacheByHandler),
		"SetHandlerWithCode": reflect.ValueOf(in.SetHandlerWithCode),
		"Succ":               reflect.ValueOf(in.Succ),
		"Text":               reflect.ValueOf(in.Text),
		"Text200":            reflect.ValueOf(in.Text200),
		"Unauthorized":       reflect.ValueOf(in.Unauthorized),
		"WithBind":           reflect.ValueOf(in.WithBind),
		"WithCORS":           reflect.ValueOf(in.WithCORS),
		"WithDefault":        reflect.ValueOf(in.WithDefault),

		// type definitions
		"CUSTOM":        reflect.ValueOf((*in.CUSTOM)(nil)),
		"Client":        reflect.ValueOf((*in.Client)(nil)),
		"FILE":          reflect.ValueOf((*in.FILE)(nil)),
		"HTML":          reflect.ValueOf((*in.HTML)(nil)),
		"IMarshal":      reflect.ValueOf((*in.IMarshal)(nil)),
		"JSON":          reflect.ValueOf((*in.JSON)(nil)),
		"Marshal":       reflect.ValueOf((*in.Marshal)(nil)),
		"Option":        reflect.ValueOf((*in.Option)(nil)),
		"READER":        reflect.ValueOf((*in.READER)(nil)),
		"Request":       reflect.ValueOf((*in.Request)(nil)),
		"Respondent":    reflect.ValueOf((*in.Respondent)(nil)),
		"Response":      reflect.ValueOf((*in.Response)(nil)),
		"ResponseCount": reflect.ValueOf((*in.ResponseCount)(nil)),
		"TEXT":          reflect.ValueOf((*in.TEXT)(nil)),
		"Writer":        reflect.ValueOf((*in.Writer)(nil)),
		"WriterOption":  reflect.ValueOf((*in.WriterOption)(nil)),

		// interface wrapper definitions
		"_Client":     reflect.ValueOf((*_github_com_injoyai_frame_middle_in_Client)(nil)),
		"_IMarshal":   reflect.ValueOf((*_github_com_injoyai_frame_middle_in_IMarshal)(nil)),
		"_Respondent": reflect.ValueOf((*_github_com_injoyai_frame_middle_in_Respondent)(nil)),
		"_Writer":     reflect.ValueOf((*_github_com_injoyai_frame_middle_in_Writer)(nil)),
	}
}

// _github_com_injoyai_frame_middle_in_Client is an interface wrapper for Client type
type _github_com_injoyai_frame_middle_in_Client struct {
	IValue                   interface{}
	WBind                    func(path string, handler http.HandlerFunc)
	WCache                   func() *maps.Generic[any, any]
	WCheckErr                func(err error, failMsg ...string)
	WCustom                  func(code int, data any, header http.Header)
	WCustom200               func(data any, h http.Header)
	WErr                     func(data any)
	WExit                    func()
	WFail                    func(data any)
	WFile                    func(name string, size int64, r io.ReadCloser)
	WFileBytes               func(name string, bs []byte)
	WFileLocal               func(name string, filename string)
	WFileReader              func(name string, r io.ReadCloser)
	WForbidden               func()
	WHtml                    func(code int, data any)
	WHtml200                 func(data any)
	WHtmlLocal               func(filename string)
	WHtmlReader              func(r io.ReadCloser)
	WJson                    func(code int, data any)
	WJson200                 func(data any)
	WJson400                 func(data any)
	WJson401                 func(data any)
	WJson403                 func(data any)
	WJson415                 func(data any)
	WJson500                 func(data any)
	WNewFailWithCode         func(code any) func(msg any)
	WNewForbiddenWithCode    func(code any) func()
	WNewSuccWithCode         func(code any) func(data any, count ...int64)
	WNewUnauthorizedWithCode func(code any) func()
	WNewWriter               func(code int, i in.IMarshal) in.Writer
	WProxy                   func(w http.ResponseWriter, r *http.Request, uri string)
	WReader                  func(code int, r io.ReadCloser)
	WReader200               func(r io.ReadCloser)
	WRecover                 func(h http.Handler) http.Handler
	WRecoverFunc             func(f http.HandlerFunc) http.Handler
	WRecoverWriter           func(e any, w http.ResponseWriter)
	WRedirect301             func(addr string)
	WRedirect302             func(addr string)
	WRedirect307             func(addr string)
	WRedirect308             func(addr string)
	WSetHandlerWithCode      func(succ any, fail any, unauthorized any, forbidden any)
	WSetWriterOption         func(f ...in.WriterOption)
	WSucc                    func(data any, count ...int64)
	WText                    func(code int, data any)
	WText200                 func(data any)
	WUnauthorized            func()
}

func (W _github_com_injoyai_frame_middle_in_Client) Bind(path string, handler http.HandlerFunc) {
	W.WBind(path, handler)
}
func (W _github_com_injoyai_frame_middle_in_Client) Cache() *maps.Generic[any, any] {
	return W.WCache()
}
func (W _github_com_injoyai_frame_middle_in_Client) CheckErr(err error, failMsg ...string) {
	W.WCheckErr(err, failMsg...)
}
func (W _github_com_injoyai_frame_middle_in_Client) Custom(code int, data any, header http.Header) {
	W.WCustom(code, data, header)
}
func (W _github_com_injoyai_frame_middle_in_Client) Custom200(data any, h http.Header) {
	W.WCustom200(data, h)
}
func (W _github_com_injoyai_frame_middle_in_Client) Err(data any) {
	W.WErr(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_middle_in_Client) Fail(data any) {
	W.WFail(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) File(name string, size int64, r io.ReadCloser) {
	W.WFile(name, size, r)
}
func (W _github_com_injoyai_frame_middle_in_Client) FileBytes(name string, bs []byte) {
	W.WFileBytes(name, bs)
}
func (W _github_com_injoyai_frame_middle_in_Client) FileLocal(name string, filename string) {
	W.WFileLocal(name, filename)
}
func (W _github_com_injoyai_frame_middle_in_Client) FileReader(name string, r io.ReadCloser) {
	W.WFileReader(name, r)
}
func (W _github_com_injoyai_frame_middle_in_Client) Forbidden() {
	W.WForbidden()
}
func (W _github_com_injoyai_frame_middle_in_Client) Html(code int, data any) {
	W.WHtml(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Html200(data any) {
	W.WHtml200(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) HtmlLocal(filename string) {
	W.WHtmlLocal(filename)
}
func (W _github_com_injoyai_frame_middle_in_Client) HtmlReader(r io.ReadCloser) {
	W.WHtmlReader(r)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json(code int, data any) {
	W.WJson(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json200(data any) {
	W.WJson200(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json400(data any) {
	W.WJson400(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json401(data any) {
	W.WJson401(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json403(data any) {
	W.WJson403(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json415(data any) {
	W.WJson415(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Json500(data any) {
	W.WJson500(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) NewFailWithCode(code any) func(msg any) {
	return W.WNewFailWithCode(code)
}
func (W _github_com_injoyai_frame_middle_in_Client) NewForbiddenWithCode(code any) func() {
	return W.WNewForbiddenWithCode(code)
}
func (W _github_com_injoyai_frame_middle_in_Client) NewSuccWithCode(code any) func(data any, count ...int64) {
	return W.WNewSuccWithCode(code)
}
func (W _github_com_injoyai_frame_middle_in_Client) NewUnauthorizedWithCode(code any) func() {
	return W.WNewUnauthorizedWithCode(code)
}
func (W _github_com_injoyai_frame_middle_in_Client) NewWriter(code int, i in.IMarshal) in.Writer {
	return W.WNewWriter(code, i)
}
func (W _github_com_injoyai_frame_middle_in_Client) Proxy(w http.ResponseWriter, r *http.Request, uri string) {
	W.WProxy(w, r, uri)
}
func (W _github_com_injoyai_frame_middle_in_Client) Reader(code int, r io.ReadCloser) {
	W.WReader(code, r)
}
func (W _github_com_injoyai_frame_middle_in_Client) Reader200(r io.ReadCloser) {
	W.WReader200(r)
}
func (W _github_com_injoyai_frame_middle_in_Client) Recover(h http.Handler) http.Handler {
	return W.WRecover(h)
}
func (W _github_com_injoyai_frame_middle_in_Client) RecoverFunc(f http.HandlerFunc) http.Handler {
	return W.WRecoverFunc(f)
}
func (W _github_com_injoyai_frame_middle_in_Client) RecoverWriter(e any, w http.ResponseWriter) {
	W.WRecoverWriter(e, w)
}
func (W _github_com_injoyai_frame_middle_in_Client) Redirect301(addr string) {
	W.WRedirect301(addr)
}
func (W _github_com_injoyai_frame_middle_in_Client) Redirect302(addr string) {
	W.WRedirect302(addr)
}
func (W _github_com_injoyai_frame_middle_in_Client) Redirect307(addr string) {
	W.WRedirect307(addr)
}
func (W _github_com_injoyai_frame_middle_in_Client) Redirect308(addr string) {
	W.WRedirect308(addr)
}
func (W _github_com_injoyai_frame_middle_in_Client) SetHandlerWithCode(succ any, fail any, unauthorized any, forbidden any) {
	W.WSetHandlerWithCode(succ, fail, unauthorized, forbidden)
}
func (W _github_com_injoyai_frame_middle_in_Client) SetWriterOption(f ...in.WriterOption) {
	W.WSetWriterOption(f...)
}
func (W _github_com_injoyai_frame_middle_in_Client) Succ(data any, count ...int64) {
	W.WSucc(data, count...)
}
func (W _github_com_injoyai_frame_middle_in_Client) Text(code int, data any) {
	W.WText(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Text200(data any) {
	W.WText200(data)
}
func (W _github_com_injoyai_frame_middle_in_Client) Unauthorized() {
	W.WUnauthorized()
}

// _github_com_injoyai_frame_middle_in_IMarshal is an interface wrapper for IMarshal type
type _github_com_injoyai_frame_middle_in_IMarshal struct {
	IValue  interface{}
	WClose  func() error
	WHeader func() http.Header
	WRead   func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_frame_middle_in_IMarshal) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_frame_middle_in_IMarshal) Header() http.Header {
	return W.WHeader()
}
func (W _github_com_injoyai_frame_middle_in_IMarshal) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}

// _github_com_injoyai_frame_middle_in_Respondent is an interface wrapper for Respondent type
type _github_com_injoyai_frame_middle_in_Respondent struct {
	IValue        interface{}
	WCheckErr     func(err error, failMsg ...string)
	WCustom       func(code int, data any, header http.Header)
	WCustom200    func(data any, h http.Header)
	WErr          func(data any)
	WExit         func()
	WFail         func(data any)
	WFile         func(name string, size int64, r io.ReadCloser)
	WFileBytes    func(name string, bs []byte)
	WFileLocal    func(name string, filename string)
	WFileReader   func(name string, r io.ReadCloser)
	WForbidden    func()
	WHtml         func(code int, data any)
	WHtml200      func(data any)
	WHtmlLocal    func(filename string)
	WHtmlReader   func(r io.ReadCloser)
	WJson         func(code int, data any)
	WJson200      func(data any)
	WJson400      func(data any)
	WJson401      func(data any)
	WJson403      func(data any)
	WJson415      func(data any)
	WJson500      func(data any)
	WNewWriter    func(code int, i in.IMarshal) in.Writer
	WReader       func(code int, r io.ReadCloser)
	WReader200    func(r io.ReadCloser)
	WRedirect301  func(addr string)
	WRedirect302  func(addr string)
	WRedirect307  func(addr string)
	WRedirect308  func(addr string)
	WSucc         func(data any, count ...int64)
	WText         func(code int, data any)
	WText200      func(data any)
	WUnauthorized func()
}

func (W _github_com_injoyai_frame_middle_in_Respondent) CheckErr(err error, failMsg ...string) {
	W.WCheckErr(err, failMsg...)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Custom(code int, data any, header http.Header) {
	W.WCustom(code, data, header)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Custom200(data any, h http.Header) {
	W.WCustom200(data, h)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Err(data any) {
	W.WErr(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Fail(data any) {
	W.WFail(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) File(name string, size int64, r io.ReadCloser) {
	W.WFile(name, size, r)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) FileBytes(name string, bs []byte) {
	W.WFileBytes(name, bs)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) FileLocal(name string, filename string) {
	W.WFileLocal(name, filename)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) FileReader(name string, r io.ReadCloser) {
	W.WFileReader(name, r)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Forbidden() {
	W.WForbidden()
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Html(code int, data any) {
	W.WHtml(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Html200(data any) {
	W.WHtml200(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) HtmlLocal(filename string) {
	W.WHtmlLocal(filename)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) HtmlReader(r io.ReadCloser) {
	W.WHtmlReader(r)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json(code int, data any) {
	W.WJson(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json200(data any) {
	W.WJson200(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json400(data any) {
	W.WJson400(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json401(data any) {
	W.WJson401(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json403(data any) {
	W.WJson403(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json415(data any) {
	W.WJson415(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Json500(data any) {
	W.WJson500(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) NewWriter(code int, i in.IMarshal) in.Writer {
	return W.WNewWriter(code, i)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Reader(code int, r io.ReadCloser) {
	W.WReader(code, r)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Reader200(r io.ReadCloser) {
	W.WReader200(r)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Redirect301(addr string) {
	W.WRedirect301(addr)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Redirect302(addr string) {
	W.WRedirect302(addr)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Redirect307(addr string) {
	W.WRedirect307(addr)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Redirect308(addr string) {
	W.WRedirect308(addr)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Succ(data any, count ...int64) {
	W.WSucc(data, count...)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Text(code int, data any) {
	W.WText(code, data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Text200(data any) {
	W.WText200(data)
}
func (W _github_com_injoyai_frame_middle_in_Respondent) Unauthorized() {
	W.WUnauthorized()
}

// _github_com_injoyai_frame_middle_in_Writer is an interface wrapper for Writer type
type _github_com_injoyai_frame_middle_in_Writer struct {
	IValue              interface{}
	WAddHeader          func(i string, v ...string)
	WClose              func() error
	WExit               func()
	WHeader             func() http.Header
	WRead               func(p []byte) (n int, err error)
	WSetCORS            func()
	WSetContentType     func(ct ...string)
	WSetContentTypeJson func()
	WSetHeader          func(i string, v ...string)
	WStatusCode         func() int
	WWrite              func(bs []byte) (int, error)
	WWriteAny           func(v any) error
	WWriteHeader        func(code int)
	WWriteJson          func(v any) error
	WWriteTo            func(w http.ResponseWriter)
}

func (W _github_com_injoyai_frame_middle_in_Writer) AddHeader(i string, v ...string) {
	W.WAddHeader(i, v...)
}
func (W _github_com_injoyai_frame_middle_in_Writer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_frame_middle_in_Writer) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_middle_in_Writer) Header() http.Header {
	return W.WHeader()
}
func (W _github_com_injoyai_frame_middle_in_Writer) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_frame_middle_in_Writer) SetCORS() {
	W.WSetCORS()
}
func (W _github_com_injoyai_frame_middle_in_Writer) SetContentType(ct ...string) {
	W.WSetContentType(ct...)
}
func (W _github_com_injoyai_frame_middle_in_Writer) SetContentTypeJson() {
	W.WSetContentTypeJson()
}
func (W _github_com_injoyai_frame_middle_in_Writer) SetHeader(i string, v ...string) {
	W.WSetHeader(i, v...)
}
func (W _github_com_injoyai_frame_middle_in_Writer) StatusCode() int {
	return W.WStatusCode()
}
func (W _github_com_injoyai_frame_middle_in_Writer) Write(bs []byte) (int, error) {
	return W.WWrite(bs)
}
func (W _github_com_injoyai_frame_middle_in_Writer) WriteAny(v any) error {
	return W.WWriteAny(v)
}
func (W _github_com_injoyai_frame_middle_in_Writer) WriteHeader(code int) {
	W.WWriteHeader(code)
}
func (W _github_com_injoyai_frame_middle_in_Writer) WriteJson(v any) error {
	return W.WWriteJson(v)
}
func (W _github_com_injoyai_frame_middle_in_Writer) WriteTo(w http.ResponseWriter) {
	W.WWriteTo(w)
}
