// Code generated by 'yaegi extract github.com/injoyai/base/types'. DO NOT EDIT.

package lib

import (
	"context"
	"github.com/injoyai/base/types"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewMemory": reflect.ValueOf(types.NewMemory),
		"Sort":      reflect.ValueOf(types.Sort),

		// type definitions
		"Bs":       reflect.ValueOf((*types.Bs)(nil)),
		"Bytes":    reflect.ValueOf((*types.Bytes)(nil)),
		"Closer":   reflect.ValueOf((*types.Closer)(nil)),
		"Debugger": reflect.ValueOf((*types.Debugger)(nil)),
		"Doner":    reflect.ValueOf((*types.Doner)(nil)),
		"Err":      reflect.ValueOf((*types.Err)(nil)),
		"F32":      reflect.ValueOf((*types.F32)(nil)),
		"F64":      reflect.ValueOf((*types.F64)(nil)),
		"Float":    reflect.ValueOf((*types.Float)(nil)),
		"Float32":  reflect.ValueOf((*types.Float32)(nil)),
		"Float64":  reflect.ValueOf((*types.Float64)(nil)),
		"Message":  reflect.ValueOf((*types.Message)(nil)),
		"Price":    reflect.ValueOf((*types.Price)(nil)),
		"Runner":   reflect.ValueOf((*types.Runner)(nil)),
		"Signaler": reflect.ValueOf((*types.Signaler)(nil)),
		"Sorter":   reflect.ValueOf((*types.Sorter)(nil)),

		// interface wrapper definitions
		"_Closer":   reflect.ValueOf((*_github_com_injoyai_base_types_Closer)(nil)),
		"_Doner":    reflect.ValueOf((*_github_com_injoyai_base_types_Doner)(nil)),
		"_Runner":   reflect.ValueOf((*_github_com_injoyai_base_types_Runner)(nil)),
		"_Signaler": reflect.ValueOf((*_github_com_injoyai_base_types_Signaler)(nil)),
		"_Sorter":   reflect.ValueOf((*_github_com_injoyai_base_types_Sorter)(nil)),
	}
}

// _github_com_injoyai_base_types_Closer is an interface wrapper for Closer type
type _github_com_injoyai_base_types_Closer struct {
	IValue        interface{}
	WClose        func() error
	WCloseWithErr func(err error) error
	WClosed       func() bool
}

func (W _github_com_injoyai_base_types_Closer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_base_types_Closer) CloseWithErr(err error) error {
	return W.WCloseWithErr(err)
}
func (W _github_com_injoyai_base_types_Closer) Closed() bool {
	return W.WClosed()
}

// _github_com_injoyai_base_types_Doner is an interface wrapper for Doner type
type _github_com_injoyai_base_types_Doner struct {
	IValue interface{}
	WDone  func() <-chan struct{}
}

func (W _github_com_injoyai_base_types_Doner) Done() <-chan struct{} {
	return W.WDone()
}

// _github_com_injoyai_base_types_Runner is an interface wrapper for Runner type
type _github_com_injoyai_base_types_Runner struct {
	IValue   interface{}
	WRun     func(ctx context.Context) error
	WRunning func() bool
}

func (W _github_com_injoyai_base_types_Runner) Run(ctx context.Context) error {
	return W.WRun(ctx)
}
func (W _github_com_injoyai_base_types_Runner) Running() bool {
	return W.WRunning()
}

// _github_com_injoyai_base_types_Signaler is an interface wrapper for Signaler type
type _github_com_injoyai_base_types_Signaler struct {
	IValue interface{}
	WDone  func() <-chan struct{}
	WErr   func() error
}

func (W _github_com_injoyai_base_types_Signaler) Done() <-chan struct{} {
	return W.WDone()
}
func (W _github_com_injoyai_base_types_Signaler) Err() error {
	return W.WErr()
}

// _github_com_injoyai_base_types_Sorter is an interface wrapper for Sorter type
type _github_com_injoyai_base_types_Sorter struct {
	IValue interface{}
	WLen   func() int
	WSwap  func(i int, j int)
}

func (W _github_com_injoyai_base_types_Sorter) Len() int {
	return W.WLen()
}
func (W _github_com_injoyai_base_types_Sorter) Swap(i int, j int) {
	W.WSwap(i, j)
}
