// Code generated by 'yaegi extract github.com/injoyai/conv/codec/xml'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec/xml"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/xml/xml"] = map[string]reflect.Value{
		// type definitions
		"Xml": reflect.ValueOf((*xml.Xml)(nil)),
	}
}
