// Code generated by 'yaegi extract github.com/injoyai/ios/v2/server/listen'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/server/listen"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/server/listen/listen"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Memory":    reflect.ValueOf(listen.Memory),
		"Run":       reflect.ValueOf(listen.Run),
		"RunMemory": reflect.ValueOf(listen.RunMemory),
		"RunUnix":   reflect.ValueOf(listen.RunUnix),
		"Unix":      reflect.ValueOf(listen.Unix),
	}
}
