// Code generated by 'yaegi extract github.com/injoyai/frame/fbr'. DO NOT EDIT.

package lib

import (
	"bufio"
	"context"
	"crypto/tls"
	"embed"
	"github.com/gofiber/fiber/v3"
	"github.com/injoyai/conv"
	"github.com/injoyai/frame/fbr"
	"github.com/injoyai/frame/middle/in"
	"github.com/valyala/fasthttp"
	"go/constant"
	"go/token"
	"io"
	"io/fs"
	"mime/multipart"
	"net/http"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/injoyai/frame/fbr/fbr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindCode":         reflect.ValueOf(fbr.BindCode),
		"BindCodes":        reflect.ValueOf(fbr.BindCodes),
		"BindHtml":         reflect.ValueOf(fbr.BindHtml),
		"Default":          reflect.ValueOf(fbr.Default),
		"DefaultUpgrader":  reflect.ValueOf(&fbr.DefaultUpgrader).Elem(),
		"New":              reflect.ValueOf(fbr.New),
		"NewCtx":           reflect.ValueOf(fbr.NewCtx),
		"NewWithStruct":    reflect.ValueOf(fbr.NewWithStruct),
		"WSBinary":         reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"WSClose":          reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"WSPing":           reflect.ValueOf(constant.MakeFromLiteral("9", token.INT, 0)),
		"WSPong":           reflect.ValueOf(constant.MakeFromLiteral("10", token.INT, 0)),
		"WSText":           reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"WithALL":          reflect.ValueOf(fbr.WithALL),
		"WithCORS":         reflect.ValueOf(fbr.WithCORS),
		"WithCache":        reflect.ValueOf(fbr.WithCache),
		"WithContext":      reflect.ValueOf(fbr.WithContext),
		"WithDELETE":       reflect.ValueOf(fbr.WithDELETE),
		"WithEmbed":        reflect.ValueOf(fbr.WithEmbed),
		"WithFS":           reflect.ValueOf(fbr.WithFS),
		"WithGET":          reflect.ValueOf(fbr.WithGET),
		"WithGroup":        reflect.ValueOf(fbr.WithGroup),
		"WithLimit":        reflect.ValueOf(fbr.WithLimit),
		"WithListenConfig": reflect.ValueOf(fbr.WithListenConfig),
		"WithLog":          reflect.ValueOf(fbr.WithLog),
		"WithLog2":         reflect.ValueOf(fbr.WithLog2),
		"WithOptions":      reflect.ValueOf(fbr.WithOptions),
		"WithPOST":         reflect.ValueOf(fbr.WithPOST),
		"WithPUT":          reflect.ValueOf(fbr.WithPUT),
		"WithPing":         reflect.ValueOf(fbr.WithPing),
		"WithPort":         reflect.ValueOf(fbr.WithPort),
		"WithPprof":        reflect.ValueOf(fbr.WithPprof),
		"WithPrintRoutes":  reflect.ValueOf(fbr.WithPrintRoutes),
		"WithRecover":      reflect.ValueOf(fbr.WithRecover),
		"WithResponseCode": reflect.ValueOf(fbr.WithResponseCode),
		"WithShutdown":     reflect.ValueOf(fbr.WithShutdown),
		"WithStatic":       reflect.ValueOf(fbr.WithStatic),
		"WithStruct":       reflect.ValueOf(fbr.WithStruct),
		"WithSwagger":      reflect.ValueOf(fbr.WithSwagger),

		// type definitions
		"Bind":         reflect.ValueOf((*fbr.Bind)(nil)),
		"Ctx":          reflect.ValueOf((*fbr.Ctx)(nil)),
		"Error":        reflect.ValueOf((*fbr.Error)(nil)),
		"Grouper":      reflect.ValueOf((*fbr.Grouper)(nil)),
		"Handler":      reflect.ValueOf((*fbr.Handler)(nil)),
		"HandlerBase":  reflect.ValueOf((*fbr.HandlerBase)(nil)),
		"ListenConfig": reflect.ValueOf((*fbr.ListenConfig)(nil)),
		"Middle":       reflect.ValueOf((*fbr.Middle)(nil)),
		"Option":       reflect.ValueOf((*fbr.Option)(nil)),
		"Requester":    reflect.ValueOf((*fbr.Requester)(nil)),
		"Respondent":   reflect.ValueOf((*fbr.Respondent)(nil)),
		"SSE":          reflect.ValueOf((*fbr.SSE)(nil)),
		"Server":       reflect.ValueOf((*fbr.Server)(nil)),
		"Websocket":    reflect.ValueOf((*fbr.Websocket)(nil)),
		"Writer":       reflect.ValueOf((*fbr.Writer)(nil)),
		"WriterOption": reflect.ValueOf((*fbr.WriterOption)(nil)),

		// interface wrapper definitions
		"_Ctx":        reflect.ValueOf((*_github_com_injoyai_frame_fbr_Ctx)(nil)),
		"_Grouper":    reflect.ValueOf((*_github_com_injoyai_frame_fbr_Grouper)(nil)),
		"_Middle":     reflect.ValueOf((*_github_com_injoyai_frame_fbr_Middle)(nil)),
		"_Requester":  reflect.ValueOf((*_github_com_injoyai_frame_fbr_Requester)(nil)),
		"_Respondent": reflect.ValueOf((*_github_com_injoyai_frame_fbr_Respondent)(nil)),
		"_SSE":        reflect.ValueOf((*_github_com_injoyai_frame_fbr_SSE)(nil)),
		"_Writer":     reflect.ValueOf((*_github_com_injoyai_frame_fbr_Writer)(nil)),
	}
}

// _github_com_injoyai_frame_fbr_Ctx is an interface wrapper for Ctx type
type _github_com_injoyai_frame_fbr_Ctx struct {
	IValue             interface{}
	WAccepts           func(offers ...string) string
	WAcceptsCharsets   func(offers ...string) string
	WAcceptsEncodings  func(offers ...string) string
	WAcceptsLanguages  func(offers ...string) string
	WApp               func() *fiber.App
	WAppend            func(field string, values ...string)
	WAttachment        func(filename ...string)
	WAutoFormat        func(body any) error
	WBaseURL           func() string
	WBind              func() *fiber.Bind
	WBody              func() []byte
	WBodyRaw           func() []byte
	WCBOR              func(data any, ctype ...string) error
	WCheckErr          func(err error, failMsg ...string)
	WClearCookie       func(key ...string)
	WClientHelloInfo   func() *tls.ClientHelloInfo
	WContext           func() context.Context
	WCookie            func(cookie *fiber.Cookie)
	WCookies           func(key string, defaultValue ...string) string
	WCustom            func(code int, data any, header http.Header)
	WCustom200         func(data any, h http.Header)
	WDownload          func(file string, filename ...string) error
	WDrop              func() error
	WErr               func(data any)
	WExit              func()
	WFail              func(data any)
	WFile              func(name string, size int64, r io.ReadCloser)
	WFileBytes         func(name string, bs []byte)
	WFileLocal         func(name string, filename string)
	WFileReader        func(name string, r io.ReadCloser)
	WForbidden         func()
	WFormFile          func(key string) (*multipart.FileHeader, error)
	WFormValue         func(key string, defaultValue ...string) string
	WFormat            func(handlers ...fiber.ResFmt) error
	WFresh             func() bool
	WGet               func(key string, defaultValue ...string) string
	WGetBool           func(key string, def ...bool) bool
	WGetByte           func(key string, def ...byte) byte
	WGetBytes          func(key string, def ...[]byte) []byte
	WGetDMap           func(key string, def ...any) *conv.Map
	WGetDuration       func(key string, def ...time.Duration) time.Duration
	WGetErr            func(key string, def ...error) error
	WGetFloat32        func(key string, def ...float32) float32
	WGetFloat64        func(key string, def ...float64) float64
	WGetGMap           func(key string, def ...map[string]any) map[string]any
	WGetHour           func(key string, def ...time.Duration) time.Duration
	WGetIMap           func(key string, def ...map[any]any) map[any]any
	WGetInt            func(key string, def ...int) int
	WGetInt16          func(key string, def ...int16) int16
	WGetInt32          func(key string, def ...int32) int32
	WGetInt64          func(key string, def ...int64) int64
	WGetInt64s         func(key string, def ...[]int64) []int64
	WGetInt8           func(key string, def ...int8) int8
	WGetInterface      func(key string, def ...any) any
	WGetInterfaces     func(key string, def ...[]any) []any
	WGetInts           func(key string, def ...[]int) []int
	WGetMicrosecond    func(key string, def ...time.Duration) time.Duration
	WGetMillisecond    func(key string, def ...time.Duration) time.Duration
	WGetMinute         func(key string, def ...time.Duration) time.Duration
	WGetReqHeaders     func() map[string][]string
	WGetRespHeader     func(key string, defaultValue ...string) string
	WGetRespHeaders    func() map[string][]string
	WGetRouteURL       func(routeName string, params fiber.Map) (string, error)
	WGetRune           func(key string, def ...rune) rune
	WGetRunes          func(key string, def ...[]rune) []rune
	WGetSMap           func(key string, def ...map[string]string) map[string]string
	WGetSecond         func(key string, def ...time.Duration) time.Duration
	WGetString         func(key string, def ...string) string
	WGetStrings        func(key string, def ...[]string) []string
	WGetUint           func(key string, def ...uint) uint
	WGetUint16         func(key string, def ...uint16) uint16
	WGetUint32         func(key string, def ...uint32) uint32
	WGetUint64         func(key string, def ...uint64) uint64
	WGetUint8          func(key string, def ...uint8) uint8
	WHost              func() string
	WHostname          func() string
	WHtml              func(code int, data any)
	WHtml200           func(data any)
	WHtmlLocal         func(filename string)
	WHtmlReader        func(r io.ReadCloser)
	WIP                func() string
	WIPs               func() []string
	WIs                func(extension string) bool
	WIsArray           func(key string) bool
	WIsBool            func(key string) bool
	WIsDefault         func(key string) bool
	WIsFloat           func(key string) bool
	WIsFromLocal       func() bool
	WIsInt             func(key string) bool
	WIsNil             func(key string) bool
	WIsNumber          func(key string) bool
	WIsPointer         func(key string) bool
	WIsProxyTrusted    func() bool
	WIsString          func(key string) bool
	WIsTime            func(key string) bool
	WJSON              func(data any, ctype ...string) error
	WJSONP             func(data any, callback ...string) error
	WJson              func(code int, data any)
	WJson200           func(data any)
	WJson400           func(data any)
	WJson401           func(data any)
	WJson403           func(data any)
	WJson415           func(data any)
	WJson500           func(data any)
	WLinks             func(link ...string)
	WLocals            func(key any, value ...any) any
	WLocation          func(path string)
	WMethod            func(override ...string) string
	WMultipartForm     func() (*multipart.Form, error)
	WNewWriter         func(code int, i in.IMarshal) in.Writer
	WNext              func() error
	WOriginalURL       func() string
	WParams            func(key string, defaultValue ...string) string
	WParse             func(ptr any)
	WPath              func(override ...string) string
	WPort              func() string
	WProtocol          func() string
	WProxy             func(url string)
	WQueries           func() map[string]string
	WQuery             func(key string, defaultValue ...string) string
	WRange             func(size int) (fiber.Range, error)
	WReader            func(code int, r io.ReadCloser)
	WReader200         func(r io.ReadCloser)
	WRedirect          func() *fiber.Redirect
	WRedirect301       func(addr string)
	WRedirect302       func(addr string)
	WRedirect307       func(addr string)
	WRedirect308       func(addr string)
	WRedirectTo        func(url string)
	WRender            func(name string, bind fiber.Map, layouts ...string) error
	WRequest           func() *fasthttp.Request
	WRequestCtx        func() *fasthttp.RequestCtx
	WReset             func(fctx *fasthttp.RequestCtx)
	WResponse          func() *fasthttp.Response
	WRestartRouting    func() error
	WRoute             func() *fiber.Route
	WSSE               func(handler func(w fbr.SSE))
	WSaveFile          func(fileheader *multipart.FileHeader, path string) error
	WSaveFileToStorage func(fileheader *multipart.FileHeader, path string, storage fiber.Storage) error
	WScheme            func() string
	WSecure            func() bool
	WSend              func(body []byte) error
	WSendFile          func(file string, config ...fiber.SendFile) error
	WSendStatus        func(status int) error
	WSendStream        func(stream io.Reader, size ...int) error
	WSendStreamWriter  func(streamWriter func(*bufio.Writer)) error
	WSendString        func(body string) error
	WSet               func(key string, val string)
	WSetContentType    func(contentType string)
	WSetContext        func(ctx context.Context)
	WSetHeader         func(k string, v string)
	WStale             func() bool
	WStatus            func(status int) fiber.Ctx
	WStream            func(handler func(w *bufio.Writer))
	WString            func() string
	WSubdomains        func(offset ...int) []string
	WSucc              func(data any, count ...int64)
	WText              func(code int, data any)
	WText200           func(data any)
	WType              func(extension string, charset ...string) fiber.Ctx
	WUnauthorized      func()
	WVary              func(fields ...string)
	WViewBind          func(vars fiber.Map) error
	WWebsocket         func(handler func(ws *fbr.Websocket))
	WWrite             func(p []byte) (int, error)
	WWriteString       func(s string) (int, error)
	WWritef            func(f string, a ...any) (int, error)
	WXHR               func() bool
	WXML               func(data any) error
}

func (W _github_com_injoyai_frame_fbr_Ctx) Accepts(offers ...string) string {
	return W.WAccepts(offers...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) AcceptsCharsets(offers ...string) string {
	return W.WAcceptsCharsets(offers...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) AcceptsEncodings(offers ...string) string {
	return W.WAcceptsEncodings(offers...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) AcceptsLanguages(offers ...string) string {
	return W.WAcceptsLanguages(offers...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) App() *fiber.App {
	return W.WApp()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Append(field string, values ...string) {
	W.WAppend(field, values...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Attachment(filename ...string) {
	W.WAttachment(filename...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) AutoFormat(body any) error {
	return W.WAutoFormat(body)
}
func (W _github_com_injoyai_frame_fbr_Ctx) BaseURL() string {
	return W.WBaseURL()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Bind() *fiber.Bind {
	return W.WBind()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Body() []byte {
	return W.WBody()
}
func (W _github_com_injoyai_frame_fbr_Ctx) BodyRaw() []byte {
	return W.WBodyRaw()
}
func (W _github_com_injoyai_frame_fbr_Ctx) CBOR(data any, ctype ...string) error {
	return W.WCBOR(data, ctype...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) CheckErr(err error, failMsg ...string) {
	W.WCheckErr(err, failMsg...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) ClearCookie(key ...string) {
	W.WClearCookie(key...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) ClientHelloInfo() *tls.ClientHelloInfo {
	return W.WClientHelloInfo()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Context() context.Context {
	return W.WContext()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Cookie(cookie *fiber.Cookie) {
	W.WCookie(cookie)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Cookies(key string, defaultValue ...string) string {
	return W.WCookies(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Custom(code int, data any, header http.Header) {
	W.WCustom(code, data, header)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Custom200(data any, h http.Header) {
	W.WCustom200(data, h)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Download(file string, filename ...string) error {
	return W.WDownload(file, filename...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Drop() error {
	return W.WDrop()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Err(data any) {
	W.WErr(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Fail(data any) {
	W.WFail(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) File(name string, size int64, r io.ReadCloser) {
	W.WFile(name, size, r)
}
func (W _github_com_injoyai_frame_fbr_Ctx) FileBytes(name string, bs []byte) {
	W.WFileBytes(name, bs)
}
func (W _github_com_injoyai_frame_fbr_Ctx) FileLocal(name string, filename string) {
	W.WFileLocal(name, filename)
}
func (W _github_com_injoyai_frame_fbr_Ctx) FileReader(name string, r io.ReadCloser) {
	W.WFileReader(name, r)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Forbidden() {
	W.WForbidden()
}
func (W _github_com_injoyai_frame_fbr_Ctx) FormFile(key string) (*multipart.FileHeader, error) {
	return W.WFormFile(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) FormValue(key string, defaultValue ...string) string {
	return W.WFormValue(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Format(handlers ...fiber.ResFmt) error {
	return W.WFormat(handlers...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Fresh() bool {
	return W.WFresh()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Get(key string, defaultValue ...string) string {
	return W.WGet(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetBool(key string, def ...bool) bool {
	return W.WGetBool(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetByte(key string, def ...byte) byte {
	return W.WGetByte(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetBytes(key string, def ...[]byte) []byte {
	return W.WGetBytes(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetDMap(key string, def ...any) *conv.Map {
	return W.WGetDMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetDuration(key string, def ...time.Duration) time.Duration {
	return W.WGetDuration(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetErr(key string, def ...error) error {
	return W.WGetErr(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetFloat32(key string, def ...float32) float32 {
	return W.WGetFloat32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetFloat64(key string, def ...float64) float64 {
	return W.WGetFloat64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetGMap(key string, def ...map[string]any) map[string]any {
	return W.WGetGMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetHour(key string, def ...time.Duration) time.Duration {
	return W.WGetHour(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetIMap(key string, def ...map[any]any) map[any]any {
	return W.WGetIMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt(key string, def ...int) int {
	return W.WGetInt(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt16(key string, def ...int16) int16 {
	return W.WGetInt16(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt32(key string, def ...int32) int32 {
	return W.WGetInt32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt64(key string, def ...int64) int64 {
	return W.WGetInt64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt64s(key string, def ...[]int64) []int64 {
	return W.WGetInt64s(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInt8(key string, def ...int8) int8 {
	return W.WGetInt8(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInterface(key string, def ...any) any {
	return W.WGetInterface(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInterfaces(key string, def ...[]any) []any {
	return W.WGetInterfaces(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetInts(key string, def ...[]int) []int {
	return W.WGetInts(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetMicrosecond(key string, def ...time.Duration) time.Duration {
	return W.WGetMicrosecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetMillisecond(key string, def ...time.Duration) time.Duration {
	return W.WGetMillisecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetMinute(key string, def ...time.Duration) time.Duration {
	return W.WGetMinute(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetReqHeaders() map[string][]string {
	return W.WGetReqHeaders()
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetRespHeader(key string, defaultValue ...string) string {
	return W.WGetRespHeader(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetRespHeaders() map[string][]string {
	return W.WGetRespHeaders()
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetRouteURL(routeName string, params fiber.Map) (string, error) {
	return W.WGetRouteURL(routeName, params)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetRune(key string, def ...rune) rune {
	return W.WGetRune(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetRunes(key string, def ...[]rune) []rune {
	return W.WGetRunes(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetSMap(key string, def ...map[string]string) map[string]string {
	return W.WGetSMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetSecond(key string, def ...time.Duration) time.Duration {
	return W.WGetSecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetString(key string, def ...string) string {
	return W.WGetString(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetStrings(key string, def ...[]string) []string {
	return W.WGetStrings(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetUint(key string, def ...uint) uint {
	return W.WGetUint(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetUint16(key string, def ...uint16) uint16 {
	return W.WGetUint16(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetUint32(key string, def ...uint32) uint32 {
	return W.WGetUint32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetUint64(key string, def ...uint64) uint64 {
	return W.WGetUint64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) GetUint8(key string, def ...uint8) uint8 {
	return W.WGetUint8(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Host() string {
	return W.WHost()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Hostname() string {
	return W.WHostname()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Html(code int, data any) {
	W.WHtml(code, data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Html200(data any) {
	W.WHtml200(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) HtmlLocal(filename string) {
	W.WHtmlLocal(filename)
}
func (W _github_com_injoyai_frame_fbr_Ctx) HtmlReader(r io.ReadCloser) {
	W.WHtmlReader(r)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IP() string {
	return W.WIP()
}
func (W _github_com_injoyai_frame_fbr_Ctx) IPs() []string {
	return W.WIPs()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Is(extension string) bool {
	return W.WIs(extension)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsArray(key string) bool {
	return W.WIsArray(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsBool(key string) bool {
	return W.WIsBool(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsDefault(key string) bool {
	return W.WIsDefault(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsFloat(key string) bool {
	return W.WIsFloat(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsFromLocal() bool {
	return W.WIsFromLocal()
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsInt(key string) bool {
	return W.WIsInt(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsNil(key string) bool {
	return W.WIsNil(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsNumber(key string) bool {
	return W.WIsNumber(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsPointer(key string) bool {
	return W.WIsPointer(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsProxyTrusted() bool {
	return W.WIsProxyTrusted()
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsString(key string) bool {
	return W.WIsString(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) IsTime(key string) bool {
	return W.WIsTime(key)
}
func (W _github_com_injoyai_frame_fbr_Ctx) JSON(data any, ctype ...string) error {
	return W.WJSON(data, ctype...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) JSONP(data any, callback ...string) error {
	return W.WJSONP(data, callback...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json(code int, data any) {
	W.WJson(code, data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json200(data any) {
	W.WJson200(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json400(data any) {
	W.WJson400(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json401(data any) {
	W.WJson401(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json403(data any) {
	W.WJson403(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json415(data any) {
	W.WJson415(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Json500(data any) {
	W.WJson500(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Links(link ...string) {
	W.WLinks(link...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Locals(key any, value ...any) any {
	return W.WLocals(key, value...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Location(path string) {
	W.WLocation(path)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Method(override ...string) string {
	return W.WMethod(override...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) MultipartForm() (*multipart.Form, error) {
	return W.WMultipartForm()
}
func (W _github_com_injoyai_frame_fbr_Ctx) NewWriter(code int, i in.IMarshal) in.Writer {
	return W.WNewWriter(code, i)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Next() error {
	return W.WNext()
}
func (W _github_com_injoyai_frame_fbr_Ctx) OriginalURL() string {
	return W.WOriginalURL()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Params(key string, defaultValue ...string) string {
	return W.WParams(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Parse(ptr any) {
	W.WParse(ptr)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Path(override ...string) string {
	return W.WPath(override...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Port() string {
	return W.WPort()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Protocol() string {
	return W.WProtocol()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Proxy(url string) {
	W.WProxy(url)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Queries() map[string]string {
	return W.WQueries()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Query(key string, defaultValue ...string) string {
	return W.WQuery(key, defaultValue...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Range(size int) (fiber.Range, error) {
	return W.WRange(size)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Reader(code int, r io.ReadCloser) {
	W.WReader(code, r)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Reader200(r io.ReadCloser) {
	W.WReader200(r)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Redirect() *fiber.Redirect {
	return W.WRedirect()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Redirect301(addr string) {
	W.WRedirect301(addr)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Redirect302(addr string) {
	W.WRedirect302(addr)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Redirect307(addr string) {
	W.WRedirect307(addr)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Redirect308(addr string) {
	W.WRedirect308(addr)
}
func (W _github_com_injoyai_frame_fbr_Ctx) RedirectTo(url string) {
	W.WRedirectTo(url)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Render(name string, bind fiber.Map, layouts ...string) error {
	return W.WRender(name, bind, layouts...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Request() *fasthttp.Request {
	return W.WRequest()
}
func (W _github_com_injoyai_frame_fbr_Ctx) RequestCtx() *fasthttp.RequestCtx {
	return W.WRequestCtx()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Reset(fctx *fasthttp.RequestCtx) {
	W.WReset(fctx)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Response() *fasthttp.Response {
	return W.WResponse()
}
func (W _github_com_injoyai_frame_fbr_Ctx) RestartRouting() error {
	return W.WRestartRouting()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Route() *fiber.Route {
	return W.WRoute()
}
func (W _github_com_injoyai_frame_fbr_Ctx) SSE(handler func(w fbr.SSE)) {
	W.WSSE(handler)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SaveFile(fileheader *multipart.FileHeader, path string) error {
	return W.WSaveFile(fileheader, path)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SaveFileToStorage(fileheader *multipart.FileHeader, path string, storage fiber.Storage) error {
	return W.WSaveFileToStorage(fileheader, path, storage)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Scheme() string {
	return W.WScheme()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Secure() bool {
	return W.WSecure()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Send(body []byte) error {
	return W.WSend(body)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SendFile(file string, config ...fiber.SendFile) error {
	return W.WSendFile(file, config...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SendStatus(status int) error {
	return W.WSendStatus(status)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SendStream(stream io.Reader, size ...int) error {
	return W.WSendStream(stream, size...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SendStreamWriter(streamWriter func(*bufio.Writer)) error {
	return W.WSendStreamWriter(streamWriter)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SendString(body string) error {
	return W.WSendString(body)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Set(key string, val string) {
	W.WSet(key, val)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SetContentType(contentType string) {
	W.WSetContentType(contentType)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SetContext(ctx context.Context) {
	W.WSetContext(ctx)
}
func (W _github_com_injoyai_frame_fbr_Ctx) SetHeader(k string, v string) {
	W.WSetHeader(k, v)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Stale() bool {
	return W.WStale()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Status(status int) fiber.Ctx {
	return W.WStatus(status)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Stream(handler func(w *bufio.Writer)) {
	W.WStream(handler)
}
func (W _github_com_injoyai_frame_fbr_Ctx) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Subdomains(offset ...int) []string {
	return W.WSubdomains(offset...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Succ(data any, count ...int64) {
	W.WSucc(data, count...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Text(code int, data any) {
	W.WText(code, data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Text200(data any) {
	W.WText200(data)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Type(extension string, charset ...string) fiber.Ctx {
	return W.WType(extension, charset...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Unauthorized() {
	W.WUnauthorized()
}
func (W _github_com_injoyai_frame_fbr_Ctx) Vary(fields ...string) {
	W.WVary(fields...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) ViewBind(vars fiber.Map) error {
	return W.WViewBind(vars)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Websocket(handler func(ws *fbr.Websocket)) {
	W.WWebsocket(handler)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Write(p []byte) (int, error) {
	return W.WWrite(p)
}
func (W _github_com_injoyai_frame_fbr_Ctx) WriteString(s string) (int, error) {
	return W.WWriteString(s)
}
func (W _github_com_injoyai_frame_fbr_Ctx) Writef(f string, a ...any) (int, error) {
	return W.WWritef(f, a...)
}
func (W _github_com_injoyai_frame_fbr_Ctx) XHR() bool {
	return W.WXHR()
}
func (W _github_com_injoyai_frame_fbr_Ctx) XML(data any) error {
	return W.WXML(data)
}

// _github_com_injoyai_frame_fbr_Grouper is an interface wrapper for Grouper type
type _github_com_injoyai_frame_fbr_Grouper struct {
	IValue         interface{}
	WALL           func(path string, handler func(c fbr.Ctx))
	WCONNECT       func(path string, handler func(c fbr.Ctx))
	WDELETE        func(path string, handler func(c fbr.Ctx))
	WEmbed         func(path string, e embed.FS)
	WFS            func(path string, fs fs.FS)
	WGET           func(path string, handler func(c fbr.Ctx))
	WGroup         func(path string, handler func(g fbr.Grouper))
	WHEAD          func(path string, handler func(c fbr.Ctx))
	WOPTIONS       func(path string, handler func(c fbr.Ctx))
	WPATCH         func(path string, handler func(c fbr.Ctx))
	WPOST          func(path string, handler func(c fbr.Ctx))
	WPUT           func(path string, handler func(c fbr.Ctx))
	WRedirect      func(path string, to string)
	WSetRespondent func(respondent in.Respondent)
	WStatic        func(path string, dir string)
	WTRACE         func(path string, handler func(c fbr.Ctx))
	WUse           func(use ...any)
}

func (W _github_com_injoyai_frame_fbr_Grouper) ALL(path string, handler func(c fbr.Ctx)) {
	W.WALL(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) CONNECT(path string, handler func(c fbr.Ctx)) {
	W.WCONNECT(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) DELETE(path string, handler func(c fbr.Ctx)) {
	W.WDELETE(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) Embed(path string, e embed.FS) {
	W.WEmbed(path, e)
}
func (W _github_com_injoyai_frame_fbr_Grouper) FS(path string, fs fs.FS) {
	W.WFS(path, fs)
}
func (W _github_com_injoyai_frame_fbr_Grouper) GET(path string, handler func(c fbr.Ctx)) {
	W.WGET(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) Group(path string, handler func(g fbr.Grouper)) {
	W.WGroup(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) HEAD(path string, handler func(c fbr.Ctx)) {
	W.WHEAD(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) OPTIONS(path string, handler func(c fbr.Ctx)) {
	W.WOPTIONS(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) PATCH(path string, handler func(c fbr.Ctx)) {
	W.WPATCH(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) POST(path string, handler func(c fbr.Ctx)) {
	W.WPOST(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) PUT(path string, handler func(c fbr.Ctx)) {
	W.WPUT(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) Redirect(path string, to string) {
	W.WRedirect(path, to)
}
func (W _github_com_injoyai_frame_fbr_Grouper) SetRespondent(respondent in.Respondent) {
	W.WSetRespondent(respondent)
}
func (W _github_com_injoyai_frame_fbr_Grouper) Static(path string, dir string) {
	W.WStatic(path, dir)
}
func (W _github_com_injoyai_frame_fbr_Grouper) TRACE(path string, handler func(c fbr.Ctx)) {
	W.WTRACE(path, handler)
}
func (W _github_com_injoyai_frame_fbr_Grouper) Use(use ...any) {
	W.WUse(use...)
}

// _github_com_injoyai_frame_fbr_Middle is an interface wrapper for Middle type
type _github_com_injoyai_frame_fbr_Middle struct {
	IValue interface{}
}

// _github_com_injoyai_frame_fbr_Requester is an interface wrapper for Requester type
type _github_com_injoyai_frame_fbr_Requester struct {
	IValue          interface{}
	WGetBool        func(key string, def ...bool) bool
	WGetByte        func(key string, def ...byte) byte
	WGetBytes       func(key string, def ...[]byte) []byte
	WGetDMap        func(key string, def ...any) *conv.Map
	WGetDuration    func(key string, def ...time.Duration) time.Duration
	WGetErr         func(key string, def ...error) error
	WGetFloat32     func(key string, def ...float32) float32
	WGetFloat64     func(key string, def ...float64) float64
	WGetGMap        func(key string, def ...map[string]any) map[string]any
	WGetHour        func(key string, def ...time.Duration) time.Duration
	WGetIMap        func(key string, def ...map[any]any) map[any]any
	WGetInt         func(key string, def ...int) int
	WGetInt16       func(key string, def ...int16) int16
	WGetInt32       func(key string, def ...int32) int32
	WGetInt64       func(key string, def ...int64) int64
	WGetInt64s      func(key string, def ...[]int64) []int64
	WGetInt8        func(key string, def ...int8) int8
	WGetInterface   func(key string, def ...any) any
	WGetInterfaces  func(key string, def ...[]any) []any
	WGetInts        func(key string, def ...[]int) []int
	WGetMicrosecond func(key string, def ...time.Duration) time.Duration
	WGetMillisecond func(key string, def ...time.Duration) time.Duration
	WGetMinute      func(key string, def ...time.Duration) time.Duration
	WGetRune        func(key string, def ...rune) rune
	WGetRunes       func(key string, def ...[]rune) []rune
	WGetSMap        func(key string, def ...map[string]string) map[string]string
	WGetSecond      func(key string, def ...time.Duration) time.Duration
	WGetString      func(key string, def ...string) string
	WGetStrings     func(key string, def ...[]string) []string
	WGetUint        func(key string, def ...uint) uint
	WGetUint16      func(key string, def ...uint16) uint16
	WGetUint32      func(key string, def ...uint32) uint32
	WGetUint64      func(key string, def ...uint64) uint64
	WGetUint8       func(key string, def ...uint8) uint8
	WIsArray        func(key string) bool
	WIsBool         func(key string) bool
	WIsDefault      func(key string) bool
	WIsFloat        func(key string) bool
	WIsInt          func(key string) bool
	WIsNil          func(key string) bool
	WIsNumber       func(key string) bool
	WIsPointer      func(key string) bool
	WIsString       func(key string) bool
	WIsTime         func(key string) bool
}

func (W _github_com_injoyai_frame_fbr_Requester) GetBool(key string, def ...bool) bool {
	return W.WGetBool(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetByte(key string, def ...byte) byte {
	return W.WGetByte(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetBytes(key string, def ...[]byte) []byte {
	return W.WGetBytes(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetDMap(key string, def ...any) *conv.Map {
	return W.WGetDMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetDuration(key string, def ...time.Duration) time.Duration {
	return W.WGetDuration(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetErr(key string, def ...error) error {
	return W.WGetErr(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetFloat32(key string, def ...float32) float32 {
	return W.WGetFloat32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetFloat64(key string, def ...float64) float64 {
	return W.WGetFloat64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetGMap(key string, def ...map[string]any) map[string]any {
	return W.WGetGMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetHour(key string, def ...time.Duration) time.Duration {
	return W.WGetHour(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetIMap(key string, def ...map[any]any) map[any]any {
	return W.WGetIMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt(key string, def ...int) int {
	return W.WGetInt(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt16(key string, def ...int16) int16 {
	return W.WGetInt16(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt32(key string, def ...int32) int32 {
	return W.WGetInt32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt64(key string, def ...int64) int64 {
	return W.WGetInt64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt64s(key string, def ...[]int64) []int64 {
	return W.WGetInt64s(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInt8(key string, def ...int8) int8 {
	return W.WGetInt8(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInterface(key string, def ...any) any {
	return W.WGetInterface(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInterfaces(key string, def ...[]any) []any {
	return W.WGetInterfaces(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetInts(key string, def ...[]int) []int {
	return W.WGetInts(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetMicrosecond(key string, def ...time.Duration) time.Duration {
	return W.WGetMicrosecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetMillisecond(key string, def ...time.Duration) time.Duration {
	return W.WGetMillisecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetMinute(key string, def ...time.Duration) time.Duration {
	return W.WGetMinute(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetRune(key string, def ...rune) rune {
	return W.WGetRune(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetRunes(key string, def ...[]rune) []rune {
	return W.WGetRunes(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetSMap(key string, def ...map[string]string) map[string]string {
	return W.WGetSMap(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetSecond(key string, def ...time.Duration) time.Duration {
	return W.WGetSecond(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetString(key string, def ...string) string {
	return W.WGetString(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetStrings(key string, def ...[]string) []string {
	return W.WGetStrings(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetUint(key string, def ...uint) uint {
	return W.WGetUint(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetUint16(key string, def ...uint16) uint16 {
	return W.WGetUint16(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetUint32(key string, def ...uint32) uint32 {
	return W.WGetUint32(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetUint64(key string, def ...uint64) uint64 {
	return W.WGetUint64(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) GetUint8(key string, def ...uint8) uint8 {
	return W.WGetUint8(key, def...)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsArray(key string) bool {
	return W.WIsArray(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsBool(key string) bool {
	return W.WIsBool(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsDefault(key string) bool {
	return W.WIsDefault(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsFloat(key string) bool {
	return W.WIsFloat(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsInt(key string) bool {
	return W.WIsInt(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsNil(key string) bool {
	return W.WIsNil(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsNumber(key string) bool {
	return W.WIsNumber(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsPointer(key string) bool {
	return W.WIsPointer(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsString(key string) bool {
	return W.WIsString(key)
}
func (W _github_com_injoyai_frame_fbr_Requester) IsTime(key string) bool {
	return W.WIsTime(key)
}

// _github_com_injoyai_frame_fbr_Respondent is an interface wrapper for Respondent type
type _github_com_injoyai_frame_fbr_Respondent struct {
	IValue        interface{}
	WCheckErr     func(err error, failMsg ...string)
	WCustom       func(code int, data any, header http.Header)
	WCustom200    func(data any, h http.Header)
	WErr          func(data any)
	WExit         func()
	WFail         func(data any)
	WFile         func(name string, size int64, r io.ReadCloser)
	WFileBytes    func(name string, bs []byte)
	WFileLocal    func(name string, filename string)
	WFileReader   func(name string, r io.ReadCloser)
	WForbidden    func()
	WHtml         func(code int, data any)
	WHtml200      func(data any)
	WHtmlLocal    func(filename string)
	WHtmlReader   func(r io.ReadCloser)
	WJson         func(code int, data any)
	WJson200      func(data any)
	WJson400      func(data any)
	WJson401      func(data any)
	WJson403      func(data any)
	WJson415      func(data any)
	WJson500      func(data any)
	WNewWriter    func(code int, i in.IMarshal) in.Writer
	WReader       func(code int, r io.ReadCloser)
	WReader200    func(r io.ReadCloser)
	WRedirect301  func(addr string)
	WRedirect302  func(addr string)
	WRedirect307  func(addr string)
	WRedirect308  func(addr string)
	WSucc         func(data any, count ...int64)
	WText         func(code int, data any)
	WText200      func(data any)
	WUnauthorized func()
}

func (W _github_com_injoyai_frame_fbr_Respondent) CheckErr(err error, failMsg ...string) {
	W.WCheckErr(err, failMsg...)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Custom(code int, data any, header http.Header) {
	W.WCustom(code, data, header)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Custom200(data any, h http.Header) {
	W.WCustom200(data, h)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Err(data any) {
	W.WErr(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_fbr_Respondent) Fail(data any) {
	W.WFail(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) File(name string, size int64, r io.ReadCloser) {
	W.WFile(name, size, r)
}
func (W _github_com_injoyai_frame_fbr_Respondent) FileBytes(name string, bs []byte) {
	W.WFileBytes(name, bs)
}
func (W _github_com_injoyai_frame_fbr_Respondent) FileLocal(name string, filename string) {
	W.WFileLocal(name, filename)
}
func (W _github_com_injoyai_frame_fbr_Respondent) FileReader(name string, r io.ReadCloser) {
	W.WFileReader(name, r)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Forbidden() {
	W.WForbidden()
}
func (W _github_com_injoyai_frame_fbr_Respondent) Html(code int, data any) {
	W.WHtml(code, data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Html200(data any) {
	W.WHtml200(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) HtmlLocal(filename string) {
	W.WHtmlLocal(filename)
}
func (W _github_com_injoyai_frame_fbr_Respondent) HtmlReader(r io.ReadCloser) {
	W.WHtmlReader(r)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json(code int, data any) {
	W.WJson(code, data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json200(data any) {
	W.WJson200(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json400(data any) {
	W.WJson400(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json401(data any) {
	W.WJson401(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json403(data any) {
	W.WJson403(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json415(data any) {
	W.WJson415(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Json500(data any) {
	W.WJson500(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) NewWriter(code int, i in.IMarshal) in.Writer {
	return W.WNewWriter(code, i)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Reader(code int, r io.ReadCloser) {
	W.WReader(code, r)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Reader200(r io.ReadCloser) {
	W.WReader200(r)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Redirect301(addr string) {
	W.WRedirect301(addr)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Redirect302(addr string) {
	W.WRedirect302(addr)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Redirect307(addr string) {
	W.WRedirect307(addr)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Redirect308(addr string) {
	W.WRedirect308(addr)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Succ(data any, count ...int64) {
	W.WSucc(data, count...)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Text(code int, data any) {
	W.WText(code, data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Text200(data any) {
	W.WText200(data)
}
func (W _github_com_injoyai_frame_fbr_Respondent) Unauthorized() {
	W.WUnauthorized()
}

// _github_com_injoyai_frame_fbr_SSE is an interface wrapper for SSE type
type _github_com_injoyai_frame_fbr_SSE struct {
	IValue       interface{}
	WWrite       func(p []byte) (n int, err error)
	WWriteAny    func(v any) error
	WWriteString func(s string) (n int, err error)
}

func (W _github_com_injoyai_frame_fbr_SSE) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
func (W _github_com_injoyai_frame_fbr_SSE) WriteAny(v any) error {
	return W.WWriteAny(v)
}
func (W _github_com_injoyai_frame_fbr_SSE) WriteString(s string) (n int, err error) {
	return W.WWriteString(s)
}

// _github_com_injoyai_frame_fbr_Writer is an interface wrapper for Writer type
type _github_com_injoyai_frame_fbr_Writer struct {
	IValue              interface{}
	WAddHeader          func(i string, v ...string)
	WClose              func() error
	WExit               func()
	WHeader             func() http.Header
	WRead               func(p []byte) (n int, err error)
	WSetCORS            func()
	WSetContentType     func(ct ...string)
	WSetContentTypeJson func()
	WSetHeader          func(i string, v ...string)
	WStatusCode         func() int
	WWrite              func(bs []byte) (int, error)
	WWriteAny           func(v any) error
	WWriteHeader        func(code int)
	WWriteJson          func(v any) error
	WWriteTo            func(w http.ResponseWriter)
}

func (W _github_com_injoyai_frame_fbr_Writer) AddHeader(i string, v ...string) {
	W.WAddHeader(i, v...)
}
func (W _github_com_injoyai_frame_fbr_Writer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_frame_fbr_Writer) Exit() {
	W.WExit()
}
func (W _github_com_injoyai_frame_fbr_Writer) Header() http.Header {
	return W.WHeader()
}
func (W _github_com_injoyai_frame_fbr_Writer) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_frame_fbr_Writer) SetCORS() {
	W.WSetCORS()
}
func (W _github_com_injoyai_frame_fbr_Writer) SetContentType(ct ...string) {
	W.WSetContentType(ct...)
}
func (W _github_com_injoyai_frame_fbr_Writer) SetContentTypeJson() {
	W.WSetContentTypeJson()
}
func (W _github_com_injoyai_frame_fbr_Writer) SetHeader(i string, v ...string) {
	W.WSetHeader(i, v...)
}
func (W _github_com_injoyai_frame_fbr_Writer) StatusCode() int {
	return W.WStatusCode()
}
func (W _github_com_injoyai_frame_fbr_Writer) Write(bs []byte) (int, error) {
	return W.WWrite(bs)
}
func (W _github_com_injoyai_frame_fbr_Writer) WriteAny(v any) error {
	return W.WWriteAny(v)
}
func (W _github_com_injoyai_frame_fbr_Writer) WriteHeader(code int) {
	W.WWriteHeader(code)
}
func (W _github_com_injoyai_frame_fbr_Writer) WriteJson(v any) error {
	return W.WWriteJson(v)
}
func (W _github_com_injoyai_frame_fbr_Writer) WriteTo(w http.ResponseWriter) {
	W.WWriteTo(w)
}
