// Code generated by 'yaegi extract github.com/injoyai/base/chans'. DO NOT EDIT.

package lib

import (
	"context"
	"github.com/injoyai/base/chans"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/injoyai/base/chans/chans"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewCoroutine":     reflect.ValueOf(chans.NewCoroutine),
		"NewCounter":       reflect.ValueOf(chans.NewCounter),
		"NewIO":            reflect.ValueOf(chans.NewIO),
		"NewLast":          reflect.ValueOf(chans.NewLast),
		"NewLimit":         reflect.ValueOf(chans.NewLimit),
		"NewLimitGo":       reflect.ValueOf(chans.NewLimitGo),
		"NewOrder":         reflect.ValueOf(chans.NewOrder),
		"NewQueueFunc":     reflect.ValueOf(chans.NewQueueFunc),
		"NewRerun":         reflect.ValueOf(chans.NewRerun),
		"NewSignal":        reflect.ValueOf(chans.NewSignal),
		"NewWaitLimit":     reflect.ValueOf(chans.NewWaitLimit),
		"TraverseInterval": reflect.ValueOf(chans.TraverseInterval),

		// type definitions
		"Coroutine":        reflect.ValueOf((*chans.Coroutine)(nil)),
		"Counter":          reflect.ValueOf((*chans.Counter)(nil)),
		"IO":               reflect.ValueOf((*chans.IO)(nil)),
		"Last":             reflect.ValueOf((*chans.Last)(nil)),
		"Limit":            reflect.ValueOf((*chans.Limit)(nil)),
		"LimitGo":          reflect.ValueOf((*chans.LimitGo)(nil)),
		"MustWriter":       reflect.ValueOf((*chans.MustWriter)(nil)),
		"Order":            reflect.ValueOf((*chans.Order)(nil)),
		"OrderNode":        reflect.ValueOf((*chans.OrderNode)(nil)),
		"QueueFunc":        reflect.ValueOf((*chans.QueueFunc)(nil)),
		"QueueFuncHandler": reflect.ValueOf((*chans.QueueFuncHandler)(nil)),
		"Rerun":            reflect.ValueOf((*chans.Rerun)(nil)),
		"Signal":           reflect.ValueOf((*chans.Signal)(nil)),
		"TryWriter":        reflect.ValueOf((*chans.TryWriter)(nil)),
		"WaitLimit":        reflect.ValueOf((*chans.WaitLimit)(nil)),

		// interface wrapper definitions
		"_Coroutine": reflect.ValueOf((*_github_com_injoyai_base_chans_Coroutine)(nil)),
		"_LimitGo":   reflect.ValueOf((*_github_com_injoyai_base_chans_LimitGo)(nil)),
		"_WaitLimit": reflect.ValueOf((*_github_com_injoyai_base_chans_WaitLimit)(nil)),
	}
}

// _github_com_injoyai_base_chans_Coroutine is an interface wrapper for Coroutine type
type _github_com_injoyai_base_chans_Coroutine struct {
	IValue      interface{}
	WGo         func(f func()) <-chan struct{}
	WGoContext  func(f func(ctx context.Context) error) <-chan struct{}
	WGoRetry    func(f func() error, retry int) <-chan struct{}
	WOnErr      func(a0 func(err error))
	WSetTimeout func(timeout time.Duration)
	WWait       func()
}

func (W _github_com_injoyai_base_chans_Coroutine) Go(f func()) <-chan struct{} {
	return W.WGo(f)
}
func (W _github_com_injoyai_base_chans_Coroutine) GoContext(f func(ctx context.Context) error) <-chan struct{} {
	return W.WGoContext(f)
}
func (W _github_com_injoyai_base_chans_Coroutine) GoRetry(f func() error, retry int) <-chan struct{} {
	return W.WGoRetry(f, retry)
}
func (W _github_com_injoyai_base_chans_Coroutine) OnErr(a0 func(err error)) {
	W.WOnErr(a0)
}
func (W _github_com_injoyai_base_chans_Coroutine) SetTimeout(timeout time.Duration) {
	W.WSetTimeout(timeout)
}
func (W _github_com_injoyai_base_chans_Coroutine) Wait() {
	W.WWait()
}

// _github_com_injoyai_base_chans_LimitGo is an interface wrapper for LimitGo type
type _github_com_injoyai_base_chans_LimitGo struct {
	IValue interface{}
	WGo    func(f func())
	WWait  func()
}

func (W _github_com_injoyai_base_chans_LimitGo) Go(f func()) {
	W.WGo(f)
}
func (W _github_com_injoyai_base_chans_LimitGo) Wait() {
	W.WWait()
}

// _github_com_injoyai_base_chans_WaitLimit is an interface wrapper for WaitLimit type
type _github_com_injoyai_base_chans_WaitLimit struct {
	IValue interface{}
	WAdd   func()
	WDone  func()
	WWait  func()
}

func (W _github_com_injoyai_base_chans_WaitLimit) Add() {
	W.WAdd()
}
func (W _github_com_injoyai_base_chans_WaitLimit) Done() {
	W.WDone()
}
func (W _github_com_injoyai_base_chans_WaitLimit) Wait() {
	W.WWait()
}
