// Code generated by 'yaegi extract github.com/injoyai/ios/v2/split'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/split"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/split/split"] = map[string]reflect.Value{
		// type definitions
		"CRC16Modbus": reflect.ValueOf((*split.CRC16Modbus)(nil)),
		"Checker":     reflect.ValueOf((*split.Checker)(nil)),
		"Length":      reflect.ValueOf((*split.Length)(nil)),
		"Prefix":      reflect.ValueOf((*split.Prefix)(nil)),
		"Prefixes":    reflect.ValueOf((*split.Prefixes)(nil)),
		"Regular":     reflect.ValueOf((*split.Regular)(nil)),
		"Split":       reflect.ValueOf((*split.Split)(nil)),
		"Suffix":      reflect.ValueOf((*split.Suffix)(nil)),
		"SumLast":     reflect.ValueOf((*split.SumLast)(nil)),

		// interface wrapper definitions
		"_Checker": reflect.ValueOf((*_github_com_injoyai_ios_v2_split_Checker)(nil)),
	}
}

// _github_com_injoyai_ios_v2_split_Checker is an interface wrapper for Checker type
type _github_com_injoyai_ios_v2_split_Checker struct {
	IValue interface{}
	WCheck func(a0 []byte) (match bool, invalid bool, err error)
}

func (W _github_com_injoyai_ios_v2_split_Checker) Check(a0 []byte) (match bool, invalid bool, err error) {
	return W.WCheck(a0)
}
