// Code generated by 'yaegi extract github.com/injoyai/conv/cfg'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/cfg"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/cfg/cfg"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Append":          reflect.ValueOf(cfg.Append),
		"Default":         reflect.ValueOf(cfg.Default),
		"GetBool":         reflect.ValueOf(cfg.GetBool),
		"GetDMap":         reflect.ValueOf(cfg.GetDMap),
		"GetDuration":     reflect.ValueOf(cfg.GetDuration),
		"GetFloat32":      reflect.ValueOf(cfg.GetFloat32),
		"GetFloat64":      reflect.ValueOf(cfg.GetFloat64),
		"GetHour":         reflect.ValueOf(cfg.GetHour),
		"GetInt":          reflect.ValueOf(cfg.GetInt),
		"GetInt64":        reflect.ValueOf(cfg.GetInt64),
		"GetInt64s":       reflect.ValueOf(cfg.GetInt64s),
		"GetInterfaces":   reflect.ValueOf(cfg.GetInterfaces),
		"GetInts":         reflect.ValueOf(cfg.GetInts),
		"GetMap":          reflect.ValueOf(cfg.GetMap),
		"GetMinute":       reflect.ValueOf(cfg.GetMinute),
		"GetSecond":       reflect.ValueOf(cfg.GetSecond),
		"GetString":       reflect.ValueOf(cfg.GetString),
		"GetStrings":      reflect.ValueOf(cfg.GetStrings),
		"Init":            reflect.ValueOf(cfg.Init),
		"New":             reflect.ValueOf(cfg.New),
		"WithAny":         reflect.ValueOf(cfg.WithAny),
		"WithDefaultFile": reflect.ValueOf(cfg.WithDefaultFile),
		"WithEnv":         reflect.ValueOf(cfg.WithEnv),
		"WithExecuteFile": reflect.ValueOf(cfg.WithExecuteFile),
		"WithFile":        reflect.ValueOf(cfg.WithFile),
		"WithIni":         reflect.ValueOf(cfg.WithIni),
		"WithJson":        reflect.ValueOf(cfg.WithJson),
		"WithToml":        reflect.ValueOf(cfg.WithToml),
		"WithYaml":        reflect.ValueOf(cfg.WithYaml),

		// type definitions
		"Entity": reflect.ValueOf((*cfg.Entity)(nil)),
		"Env":    reflect.ValueOf((*cfg.Env)(nil)),
		"Flag":   reflect.ValueOf((*cfg.Flag)(nil)),
	}
}
