// Code generated by 'yaegi extract github.com/injoyai/conv/codec/ini'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec/ini"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/ini/ini"] = map[string]reflect.Value{
		// type definitions
		"Ini": reflect.ValueOf((*ini.Ini)(nil)),
	}
}
