// Code generated by 'yaegi extract github.com/injoyai/base/crypt'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/crypt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DealLength": reflect.ValueOf(crypt.DealLength),
		"Hmac":       reflect.ValueOf(crypt.Hmac),
		"New":        reflect.ValueOf(crypt.New),
		"Padding":    reflect.ValueOf(crypt.Padding),

		// type definitions
		"Entity": reflect.ValueOf((*crypt.Entity)(nil)),
	}
}
