// Code generated by 'yaegi extract github.com/injoyai/base/coding/json'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/coding/json"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/coding/json/json"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Marshal":         reflect.ValueOf(&json.Marshal).Elem(),
		"MarshalIndent":   reflect.ValueOf(&json.MarshalIndent).Elem(),
		"MarshalToString": reflect.ValueOf(&json.MarshalToString).Elem(),
		"NewDecoder":      reflect.ValueOf(&json.NewDecoder).Elem(),
		"NewEncoder":      reflect.ValueOf(&json.NewEncoder).Elem(),
		"Unmarshal":       reflect.ValueOf(&json.Unmarshal).Elem(),
		"Valid":           reflect.ValueOf(&json.Valid).Elem(),

		// type definitions
		"Entity": reflect.ValueOf((*json.Entity)(nil)),
	}
}
