// Code generated by 'yaegi extract github.com/injoyai/base/crypt/aes'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/aes"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/aes/aes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DecryptCBC":       reflect.ValueOf(aes.DecryptCBC),
		"DecryptCBCBase64": reflect.ValueOf(aes.DecryptCBCBase64),
		"DecryptCBCBytes":  reflect.ValueOf(aes.DecryptCBCBytes),
		"DecryptCBCHEX":    reflect.ValueOf(aes.DecryptCBCHEX),
		"DecryptCBCString": reflect.ValueOf(aes.DecryptCBCString),
		"DecryptECB":       reflect.ValueOf(aes.DecryptECB),
		"DecryptECBBase64": reflect.ValueOf(aes.DecryptECBBase64),
		"DecryptECBBytes":  reflect.ValueOf(aes.DecryptECBBytes),
		"DecryptECBHEX":    reflect.ValueOf(aes.DecryptECBHEX),
		"DecryptECBString": reflect.ValueOf(aes.DecryptECBString),
		"EncryptCBC":       reflect.ValueOf(aes.EncryptCBC),
		"EncryptCBCBase64": reflect.ValueOf(aes.EncryptCBCBase64),
		"EncryptCBCBytes":  reflect.ValueOf(aes.EncryptCBCBytes),
		"EncryptCBCHEX":    reflect.ValueOf(aes.EncryptCBCHEX),
		"EncryptCBCString": reflect.ValueOf(aes.EncryptCBCString),
		"EncryptECB":       reflect.ValueOf(aes.EncryptECB),
		"EncryptECBBase64": reflect.ValueOf(aes.EncryptECBBase64),
		"EncryptECBBytes":  reflect.ValueOf(aes.EncryptECBBytes),
		"EncryptECBHEX":    reflect.ValueOf(aes.EncryptECBHEX),
		"EncryptECBString": reflect.ValueOf(aes.EncryptECBString),
		"PKCS7Padding":     reflect.ValueOf(aes.PKCS7Padding),
		"PKCS7UnPadding":   reflect.ValueOf(aes.PKCS7UnPadding),
	}
}
