// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/mqtt'. DO NOT EDIT.

package lib

import (
	pahomqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/injoyai/ios/v2/module/mqtt"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/mqtt/mqtt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":         reflect.ValueOf(mqtt.Dial),
		"DialClient":   reflect.ValueOf(mqtt.DialClient),
		"NewDial":      reflect.ValueOf(mqtt.NewDial),
		"NewListen":    reflect.ValueOf(mqtt.NewListen),
		"NewNetListen": reflect.ValueOf(mqtt.NewNetListen),
		"WithBase":     reflect.ValueOf(mqtt.WithBase),

		// type definitions
		"BaseConfig": reflect.ValueOf((*mqtt.BaseConfig)(nil)),
		"Client":     reflect.ValueOf((*mqtt.Client)(nil)),
		"Config":     reflect.ValueOf((*mqtt.Config)(nil)),
		"Conn":       reflect.ValueOf((*mqtt.Conn)(nil)),
		"Connect":    reflect.ValueOf((*mqtt.Connect)(nil)),
		"Message":    reflect.ValueOf((*mqtt.Message)(nil)),
		"Publish":    reflect.ValueOf((*mqtt.Publish)(nil)),
		"Server":     reflect.ValueOf((*mqtt.Server)(nil)),
		"Subscribe":  reflect.ValueOf((*mqtt.Subscribe)(nil)),

		// interface wrapper definitions
		"_Connect": reflect.ValueOf((*_github_com_injoyai_ios_v2_module_mqtt_Connect)(nil)),
	}
}

// _github_com_injoyai_ios_v2_module_mqtt_Connect is an interface wrapper for Connect type
type _github_com_injoyai_ios_v2_module_mqtt_Connect struct {
	IValue             interface{}
	WAddRoute          func(topic string, callback pahomqtt.MessageHandler)
	WConnect           func() pahomqtt.Token
	WDisconnect        func(quiesce uint)
	WIsConnected       func() bool
	WIsConnectionOpen  func() bool
	WOptionsReader     func() pahomqtt.ClientOptionsReader
	WPublish           func(topic string, qos byte, retained bool, payload interface{}) pahomqtt.Token
	WSubscribe         func(topic string, qos byte, callback pahomqtt.MessageHandler) pahomqtt.Token
	WSubscribeMultiple func(filters map[string]byte, callback pahomqtt.MessageHandler) pahomqtt.Token
	WUnsubscribe       func(topics ...string) pahomqtt.Token
}

func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) AddRoute(topic string, callback pahomqtt.MessageHandler) {
	W.WAddRoute(topic, callback)
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) Connect() pahomqtt.Token {
	return W.WConnect()
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) Disconnect(quiesce uint) {
	W.WDisconnect(quiesce)
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) IsConnected() bool {
	return W.WIsConnected()
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) IsConnectionOpen() bool {
	return W.WIsConnectionOpen()
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) OptionsReader() pahomqtt.ClientOptionsReader {
	return W.WOptionsReader()
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) Publish(topic string, qos byte, retained bool, payload interface{}) pahomqtt.Token {
	return W.WPublish(topic, qos, retained, payload)
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) Subscribe(topic string, qos byte, callback pahomqtt.MessageHandler) pahomqtt.Token {
	return W.WSubscribe(topic, qos, callback)
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) SubscribeMultiple(filters map[string]byte, callback pahomqtt.MessageHandler) pahomqtt.Token {
	return W.WSubscribeMultiple(filters, callback)
}
func (W _github_com_injoyai_ios_v2_module_mqtt_Connect) Unsubscribe(topics ...string) pahomqtt.Token {
	return W.WUnsubscribe(topics...)
}
