// Code generated by 'yaegi extract github.com/injoyai/conv/codec/toml'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec/toml"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/toml/toml"] = map[string]reflect.Value{
		// type definitions
		"Toml": reflect.ValueOf((*toml.Toml)(nil)),
	}
}
