// Code generated by 'yaegi extract github.com/injoyai/base/crypt/tls'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/tls"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/tls/tls"] = map[string]reflect.Value{
		// type definitions
		"Config": reflect.ValueOf((*tls.Config)(nil)),
	}
}
