// Code generated by 'yaegi extract github.com/injoyai/base/crypt/sha'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/sha"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/sha/sha"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Encrypt1":         reflect.ValueOf(sha.Encrypt1),
		"Encrypt1Base64":   reflect.ValueOf(sha.Encrypt1Base64),
		"Encrypt1Bytes":    reflect.ValueOf(sha.Encrypt1Bytes),
		"Encrypt1HEX":      reflect.ValueOf(sha.Encrypt1HEX),
		"Encrypt1String":   reflect.ValueOf(sha.Encrypt1String),
		"Encrypt256":       reflect.ValueOf(sha.Encrypt256),
		"Encrypt256Base64": reflect.ValueOf(sha.Encrypt256Base64),
		"Encrypt256Bytes":  reflect.ValueOf(sha.Encrypt256Bytes),
		"Encrypt256HEX":    reflect.ValueOf(sha.Encrypt256HEX),
		"Encrypt256String": reflect.ValueOf(sha.Encrypt256String),
		"Encrypt512":       reflect.ValueOf(sha.Encrypt512),
		"Encrypt512Base64": reflect.ValueOf(sha.Encrypt512Base64),
		"Encrypt512Bytes":  reflect.ValueOf(sha.Encrypt512Bytes),
		"Encrypt512HEX":    reflect.ValueOf(sha.Encrypt512HEX),
		"Encrypt512String": reflect.ValueOf(sha.Encrypt512String),
		"Hmac1":            reflect.ValueOf(sha.Hmac1),
		"Hmac1Base64":      reflect.ValueOf(sha.Hmac1Base64),
		"Hmac1Bytes":       reflect.ValueOf(sha.Hmac1Bytes),
		"Hmac1HEX":         reflect.ValueOf(sha.Hmac1HEX),
		"Hmac1HEXBase64":   reflect.ValueOf(sha.Hmac1HEXBase64),
		"Hmac1String":      reflect.ValueOf(sha.Hmac1String),
		"Hmac256":          reflect.ValueOf(sha.Hmac256),
		"Hmac256Base64":    reflect.ValueOf(sha.Hmac256Base64),
		"Hmac256Bytes":     reflect.ValueOf(sha.Hmac256Bytes),
		"Hmac256HEX":       reflect.ValueOf(sha.Hmac256HEX),
		"Hmac256HEXBase64": reflect.ValueOf(sha.Hmac256HEXBase64),
		"Hmac256String":    reflect.ValueOf(sha.Hmac256String),
		"Hmac512":          reflect.ValueOf(sha.Hmac512),
		"Hmac512Base64":    reflect.ValueOf(sha.Hmac512Base64),
		"Hmac512Bytes":     reflect.ValueOf(sha.Hmac512Bytes),
		"Hmac512HEX":       reflect.ValueOf(sha.Hmac512HEX),
		"Hmac512HEXBase64": reflect.ValueOf(sha.Hmac512HEXBase64),
		"Hmac512String":    reflect.ValueOf(sha.Hmac512String),
	}
}
