// Code generated by 'yaegi extract github.com/injoyai/base/maps/timeout'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/maps/timeout"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/maps/timeout/timeout"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(timeout.New),
	}
}
