// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/sse'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/sse"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/sse/sse"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":             reflect.ValueOf(sse.Dial),
		"NewDial":          reflect.ValueOf(sse.NewDial),
		"NewHandlerListen": reflect.ValueOf(sse.NewHandlerListen),
		"NewListen":        reflect.ValueOf(sse.NewListen),

		// type definitions
		"Args":   reflect.ValueOf((*sse.Args)(nil)),
		"Client": reflect.ValueOf((*sse.Client)(nil)),
		"Server": reflect.ValueOf((*sse.Server)(nil)),
	}
}
