// Code generated by 'yaegi extract github.com/injoyai/base/coding'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/coding"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/coding/coding"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DecodeASCII":      reflect.ValueOf(coding.DecodeASCII),
		"DecodeBase64":     reflect.ValueOf(coding.DecodeBase64),
		"DecodeHEX":        reflect.ValueOf(coding.DecodeHEX),
		"EncodeASCII":      reflect.ValueOf(coding.EncodeASCII),
		"EncodeBase64":     reflect.ValueOf(coding.EncodeBase64),
		"EncodeHEX":        reflect.ValueOf(coding.EncodeHEX),
		"JsonMarshal":      reflect.ValueOf(&coding.JsonMarshal).Elem(),
		"JsonUnmarshal":    reflect.ValueOf(&coding.JsonUnmarshal).Elem(),
		"MsgpackMarshal":   reflect.ValueOf(coding.MsgpackMarshal),
		"MsgpackUnmarshal": reflect.ValueOf(coding.MsgpackUnmarshal),
		"ProtoMarshal":     reflect.ValueOf(&coding.ProtoMarshal).Elem(),
		"ProtoUnmarshal":   reflect.ValueOf(&coding.ProtoUnmarshal).Elem(),
		"TomlMarshal":      reflect.ValueOf(&coding.TomlMarshal).Elem(),
		"TomlUnmarshal":    reflect.ValueOf(&coding.TomlUnmarshal).Elem(),
		"XmlMarshal":       reflect.ValueOf(&coding.XmlMarshal).Elem(),
		"XmlUnmarshal":     reflect.ValueOf(&coding.XmlUnmarshal).Elem(),
		"YamlMarshal":      reflect.ValueOf(&coding.YamlMarshal).Elem(),
		"YamlUnmarshal":    reflect.ValueOf(&coding.YamlUnmarshal).Elem(),

		// type definitions
		"ASCII":     reflect.ValueOf((*coding.ASCII)(nil)),
		"Base64":    reflect.ValueOf((*coding.Base64)(nil)),
		"Coding":    reflect.ValueOf((*coding.Coding)(nil)),
		"Decoder":   reflect.ValueOf((*coding.Decoder)(nil)),
		"Encoder":   reflect.ValueOf((*coding.Encoder)(nil)),
		"HEX":       reflect.ValueOf((*coding.HEX)(nil)),
		"IMarshal":  reflect.ValueOf((*coding.IMarshal)(nil)),
		"Json":      reflect.ValueOf((*coding.Json)(nil)),
		"Marshal":   reflect.ValueOf((*coding.Marshal)(nil)),
		"Msgpack":   reflect.ValueOf((*coding.Msgpack)(nil)),
		"Proto":     reflect.ValueOf((*coding.Proto)(nil)),
		"Toml":      reflect.ValueOf((*coding.Toml)(nil)),
		"Unmarshal": reflect.ValueOf((*coding.Unmarshal)(nil)),
		"Xml":       reflect.ValueOf((*coding.Xml)(nil)),
		"Yaml":      reflect.ValueOf((*coding.Yaml)(nil)),

		// interface wrapper definitions
		"_Coding":    reflect.ValueOf((*_github_com_injoyai_base_coding_Coding)(nil)),
		"_Decoder":   reflect.ValueOf((*_github_com_injoyai_base_coding_Decoder)(nil)),
		"_Encoder":   reflect.ValueOf((*_github_com_injoyai_base_coding_Encoder)(nil)),
		"_IMarshal":  reflect.ValueOf((*_github_com_injoyai_base_coding_IMarshal)(nil)),
		"_Marshal":   reflect.ValueOf((*_github_com_injoyai_base_coding_Marshal)(nil)),
		"_Unmarshal": reflect.ValueOf((*_github_com_injoyai_base_coding_Unmarshal)(nil)),
	}
}

// _github_com_injoyai_base_coding_Coding is an interface wrapper for Coding type
type _github_com_injoyai_base_coding_Coding struct {
	IValue  interface{}
	WDecode func(a0 []byte) ([]byte, error)
	WEncode func(a0 []byte) string
}

func (W _github_com_injoyai_base_coding_Coding) Decode(a0 []byte) ([]byte, error) {
	return W.WDecode(a0)
}
func (W _github_com_injoyai_base_coding_Coding) Encode(a0 []byte) string {
	return W.WEncode(a0)
}

// _github_com_injoyai_base_coding_Decoder is an interface wrapper for Decoder type
type _github_com_injoyai_base_coding_Decoder struct {
	IValue  interface{}
	WDecode func(a0 []byte) ([]byte, error)
}

func (W _github_com_injoyai_base_coding_Decoder) Decode(a0 []byte) ([]byte, error) {
	return W.WDecode(a0)
}

// _github_com_injoyai_base_coding_Encoder is an interface wrapper for Encoder type
type _github_com_injoyai_base_coding_Encoder struct {
	IValue  interface{}
	WEncode func(a0 []byte) string
}

func (W _github_com_injoyai_base_coding_Encoder) Encode(a0 []byte) string {
	return W.WEncode(a0)
}

// _github_com_injoyai_base_coding_IMarshal is an interface wrapper for IMarshal type
type _github_com_injoyai_base_coding_IMarshal struct {
	IValue     interface{}
	WMarshal   func(a0 any) ([]byte, error)
	WUnmarshal func(a0 []byte, a1 any) error
}

func (W _github_com_injoyai_base_coding_IMarshal) Marshal(a0 any) ([]byte, error) {
	return W.WMarshal(a0)
}
func (W _github_com_injoyai_base_coding_IMarshal) Unmarshal(a0 []byte, a1 any) error {
	return W.WUnmarshal(a0, a1)
}

// _github_com_injoyai_base_coding_Marshal is an interface wrapper for Marshal type
type _github_com_injoyai_base_coding_Marshal struct {
	IValue   interface{}
	WMarshal func(a0 any) ([]byte, error)
}

func (W _github_com_injoyai_base_coding_Marshal) Marshal(a0 any) ([]byte, error) {
	return W.WMarshal(a0)
}

// _github_com_injoyai_base_coding_Unmarshal is an interface wrapper for Unmarshal type
type _github_com_injoyai_base_coding_Unmarshal struct {
	IValue     interface{}
	WUnmarshal func(a0 []byte, a1 any) error
}

func (W _github_com_injoyai_base_coding_Unmarshal) Unmarshal(a0 []byte, a1 any) error {
	return W.WUnmarshal(a0, a1)
}
