// Code generated by 'yaegi extract github.com/injoyai/ios/v2/client/dial'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/client/dial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/client/dial/dial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Memory":       reflect.ValueOf(dial.Memory),
		"Run":          reflect.ValueOf(dial.Run),
		"RunMemory":    reflect.ValueOf(dial.RunMemory),
		"RunTCP":       reflect.ValueOf(dial.RunTCP),
		"RunUDP":       reflect.ValueOf(dial.RunUDP),
		"RunUnix":      reflect.ValueOf(dial.RunUnix),
		"RunWebsocket": reflect.ValueOf(dial.RunWebsocket),
		"TCP":          reflect.ValueOf(dial.TCP),
		"UDP":          reflect.ValueOf(dial.UDP),
		"Unix":         reflect.ValueOf(dial.Unix),
		"Websocket":    reflect.ValueOf(dial.Websocket),
		"With":         reflect.ValueOf(dial.With),
	}
}
