// Code generated by 'yaegi extract github.com/injoyai/base/crypt/md5'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/md5"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/md5/md5"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Encrypt":       reflect.ValueOf(md5.Encrypt),
		"EncryptBase64": reflect.ValueOf(md5.EncryptBase64),
		"EncryptBytes":  reflect.ValueOf(md5.EncryptBytes),
		"EncryptHEX":    reflect.ValueOf(md5.EncryptHEX),
		"EncryptString": reflect.ValueOf(md5.EncryptString),
		"Hmac":          reflect.ValueOf(md5.Hmac),
		"HmacBase64":    reflect.ValueOf(md5.HmacBase64),
		"HmacBytes":     reflect.ValueOf(md5.HmacBytes),
		"HmacHEX":       reflect.ValueOf(md5.HmacHEX),
		"HmacString":    reflect.ValueOf(md5.HmacString),
	}
}
