// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/websocket'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/websocket"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/websocket/websocket"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":         reflect.ValueOf(websocket.Dial),
		"NewDial":      reflect.ValueOf(websocket.NewDial),
		"NewNetListen": reflect.ValueOf(websocket.NewNetListen),

		// type definitions
		"Client": reflect.ValueOf((*websocket.Client)(nil)),
		"Conn":   reflect.ValueOf((*websocket.Conn)(nil)),
		"Dialer": reflect.ValueOf((*websocket.Dialer)(nil)),
		"Server": reflect.ValueOf((*websocket.Server)(nil)),
	}
}
