// Code generated by 'yaegi extract github.com/injoyai/logs/v2'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/logs/v2"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/logs/v2/logs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddWriter":               reflect.ValueOf(logs.AddWriter),
		"Debug":                   reflect.ValueOf(logs.Debug),
		"Debugf":                  reflect.ValueOf(logs.Debugf),
		"DefaultDebug":            reflect.ValueOf(&logs.DefaultDebug).Elem(),
		"DefaultErr":              reflect.ValueOf(&logs.DefaultErr).Elem(),
		"DefaultFormatter":        reflect.ValueOf(&logs.DefaultFormatter).Elem(),
		"DefaultInfo":             reflect.ValueOf(&logs.DefaultInfo).Elem(),
		"DefaultRead":             reflect.ValueOf(&logs.DefaultRead).Elem(),
		"DefaultTrace":            reflect.ValueOf(&logs.DefaultTrace).Elem(),
		"DefaultWarn":             reflect.ValueOf(&logs.DefaultWarn).Elem(),
		"DefaultWrite":            reflect.ValueOf(&logs.DefaultWrite).Elem(),
		"DialTCP":                 reflect.ValueOf(logs.DialTCP),
		"EnableStdoutFilter":      reflect.ValueOf(logs.EnableStdoutFilter),
		"Err":                     reflect.ValueOf(logs.Err),
		"Errf":                    reflect.ValueOf(logs.Errf),
		"Error":                   reflect.ValueOf(logs.Error),
		"Errorf":                  reflect.ValueOf(logs.Errorf),
		"Fatal":                   reflect.ValueOf(logs.Fatal),
		"Fatalf":                  reflect.ValueOf(logs.Fatalf),
		"Info":                    reflect.ValueOf(logs.Info),
		"Infof":                   reflect.ValueOf(logs.Infof),
		"JsonFormatter":           reflect.ValueOf(&logs.JsonFormatter).Elem(),
		"LevelAll":                reflect.ValueOf(logs.LevelAll),
		"LevelDebug":              reflect.ValueOf(logs.LevelDebug),
		"LevelError":              reflect.ValueOf(logs.LevelError),
		"LevelInfo":               reflect.ValueOf(logs.LevelInfo),
		"LevelNone":               reflect.ValueOf(logs.LevelNone),
		"LevelRead":               reflect.ValueOf(logs.LevelRead),
		"LevelTrace":              reflect.ValueOf(logs.LevelTrace),
		"LevelWarn":               reflect.ValueOf(logs.LevelWarn),
		"LevelWrite":              reflect.ValueOf(logs.LevelWrite),
		"Log":                     reflect.ValueOf(logs.Log),
		"LogCtx":                  reflect.ValueOf(logs.LogCtx),
		"New":                     reflect.ValueOf(logs.New),
		"NewCarriageReturnWriter": reflect.ValueOf(logs.NewCarriageReturnWriter),
		"NewEntity":               reflect.ValueOf(logs.NewEntity),
		"NewFile":                 reflect.ValueOf(logs.NewFile),
		"NewFilter":               reflect.ValueOf(logs.NewFilter),
		"NewHTTPClient":           reflect.ValueOf(logs.NewHTTPClient),
		"NewTCPClient":            reflect.ValueOf(logs.NewTCPClient),
		"NewTCPServer":            reflect.ValueOf(logs.NewTCPServer),
		"NewWriteColor":           reflect.ValueOf(logs.NewWriteColor),
		"Panic":                   reflect.ValueOf(logs.Panic),
		"PanicErr":                reflect.ValueOf(logs.PanicErr),
		"Panicf":                  reflect.ValueOf(logs.Panicf),
		"ParseLevel":              reflect.ValueOf(logs.ParseLevel),
		"PrintErr":                reflect.ValueOf(logs.PrintErr),
		"Read":                    reflect.ValueOf(logs.Read),
		"Readf":                   reflect.ValueOf(logs.Readf),
		"SetCaller":               reflect.ValueOf(logs.SetCaller),
		"SetFormatter":            reflect.ValueOf(logs.SetFormatter),
		"SetFormatterWithDefault": reflect.ValueOf(logs.SetFormatterWithDefault),
		"SetFormatterWithTime":    reflect.ValueOf(logs.SetFormatterWithTime),
		"SetLevel":                reflect.ValueOf(logs.SetLevel),
		"SetLevelWithAll":         reflect.ValueOf(logs.SetLevelWithAll),
		"SetShowColor":            reflect.ValueOf(logs.SetShowColor),
		"SetWriter":               reflect.ValueOf(logs.SetWriter),
		"Spend":                   reflect.ValueOf(logs.Spend),
		"Stdout":                  reflect.ValueOf(&logs.Stdout).Elem(),
		"StopStdoutFilter":        reflect.ValueOf(logs.StopStdoutFilter),
		"StringLevel":             reflect.ValueOf(logs.StringLevel),
		"TimeFormatter":           reflect.ValueOf(&logs.TimeFormatter).Elem(),
		"Trace":                   reflect.ValueOf(logs.Trace),
		"Tracef":                  reflect.ValueOf(logs.Tracef),
		"Trunk":                   reflect.ValueOf(&logs.Trunk).Elem(),
		"Warn":                    reflect.ValueOf(logs.Warn),
		"Warnf":                   reflect.ValueOf(logs.Warnf),
		"With":                    reflect.ValueOf(logs.With),
		"WithCompress":            reflect.ValueOf(logs.WithCompress),
		"WithHTTPClient":          reflect.ValueOf(logs.WithHTTPClient),
		"WithInsecureSkipVerify":  reflect.ValueOf(logs.WithInsecureSkipVerify),
		"WithLocalTime":           reflect.ValueOf(logs.WithLocalTime),
		"WithMaxAge":              reflect.ValueOf(logs.WithMaxAge),
		"WithMaxBackups":          reflect.ValueOf(logs.WithMaxBackups),
		"WithMaxSize":             reflect.ValueOf(logs.WithMaxSize),
		"WithTimeout":             reflect.ValueOf(logs.WithTimeout),
		"Write":                   reflect.ValueOf(logs.Write),
		"WriteToHTTPServer":       reflect.ValueOf(logs.WriteToHTTPServer),
		"WriteToTCPClient":        reflect.ValueOf(logs.WriteToTCPClient),
		"WriteToTCPServer":        reflect.ValueOf(logs.WriteToTCPServer),
		"Writef":                  reflect.ValueOf(logs.Writef),

		// type definitions
		"Chan":         reflect.ValueOf((*logs.Chan)(nil)),
		"ColorWriter":  reflect.ValueOf((*logs.ColorWriter)(nil)),
		"Entity":       reflect.ValueOf((*logs.Entity)(nil)),
		"FileOption":   reflect.ValueOf((*logs.FileOption)(nil)),
		"FileWriter":   reflect.ValueOf((*logs.FileWriter)(nil)),
		"Filter":       reflect.ValueOf((*logs.Filter)(nil)),
		"FormatFunc":   reflect.ValueOf((*logs.FormatFunc)(nil)),
		"FormatRecord": reflect.ValueOf((*logs.FormatRecord)(nil)),
		"Formatter":    reflect.ValueOf((*logs.Formatter)(nil)),
		"HTTPOption":   reflect.ValueOf((*logs.HTTPOption)(nil)),
		"Level":        reflect.ValueOf((*logs.Level)(nil)),
		"Logger":       reflect.ValueOf((*logs.Logger)(nil)),
		"TCPDialer":    reflect.ValueOf((*logs.TCPDialer)(nil)),

		// interface wrapper definitions
		"_ColorWriter": reflect.ValueOf((*_github_com_injoyai_logs_v2_ColorWriter)(nil)),
		"_Formatter":   reflect.ValueOf((*_github_com_injoyai_logs_v2_Formatter)(nil)),
	}
}

// _github_com_injoyai_logs_v2_ColorWriter is an interface wrapper for ColorWriter type
type _github_com_injoyai_logs_v2_ColorWriter struct {
	IValue interface{}
	WColor func() bool
}

func (W _github_com_injoyai_logs_v2_ColorWriter) Color() bool {
	return W.WColor()
}

// _github_com_injoyai_logs_v2_Formatter is an interface wrapper for Formatter type
type _github_com_injoyai_logs_v2_Formatter struct {
	IValue  interface{}
	WFormat func(r *logs.FormatRecord) string
}

func (W _github_com_injoyai_logs_v2_Formatter) Format(r *logs.FormatRecord) string {
	return W.WFormat(r)
}
