// Code generated by 'yaegi extract github.com/injoyai/base/str'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/str"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/str/str"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bool":           reflect.ValueOf(&str.Bool).Elem(),
		"Bytes":          reflect.ValueOf(str.Bytes),
		"Contains":       reflect.ValueOf(&str.Contains).Elem(),
		"Count":          reflect.ValueOf(&str.Count).Elem(),
		"CropFirst":      reflect.ValueOf(str.CropFirst),
		"CropLast":       reflect.ValueOf(str.CropLast),
		"FindCommon":     reflect.ValueOf(str.FindCommon),
		"Float32":        reflect.ValueOf(&str.Float32).Elem(),
		"Float64":        reflect.ValueOf(&str.Float64).Elem(),
		"GB18030ToUtf8":  reflect.ValueOf(str.GB18030ToUtf8),
		"GbkToUtf8":      reflect.ValueOf(str.GbkToUtf8),
		"GetLine":        reflect.ValueOf(str.GetLine),
		"GetSplit":       reflect.ValueOf(str.GetSplit),
		"HZGB2312ToUtf8": reflect.ValueOf(str.HZGB2312ToUtf8),
		"HasPrefix":      reflect.ValueOf(&str.HasPrefix).Elem(),
		"HasRepeat":      reflect.ValueOf(str.HasRepeat),
		"HasSuffix":      reflect.ValueOf(&str.HasSuffix).Elem(),
		"Index":          reflect.ValueOf(&str.Index).Elem(),
		"Int":            reflect.ValueOf(&str.Int).Elem(),
		"Int16":          reflect.ValueOf(&str.Int16).Elem(),
		"Int32":          reflect.ValueOf(&str.Int32).Elem(),
		"Int64":          reflect.ValueOf(&str.Int64).Elem(),
		"Int8":           reflect.ValueOf(&str.Int8).Elem(),
		"Interface":      reflect.ValueOf(str.Interface),
		"IsBegin":        reflect.ValueOf(&str.IsBegin).Elem(),
		"IsEnd":          reflect.ValueOf(&str.IsEnd).Elem(),
		"Join":           reflect.ValueOf(&str.Join).Elem(),
		"MustSplitN":     reflect.ValueOf(str.MustSplitN),
		"NewReader":      reflect.ValueOf(&str.NewReader).Elem(),
		"Pointer":        reflect.ValueOf(str.Pointer),
		"Rand":           reflect.ValueOf(str.Rand),
		"ReplaceAll":     reflect.ValueOf(&str.ReplaceAll).Elem(),
		"Reverse":        reflect.ValueOf(str.Reverse),
		"Select":         reflect.ValueOf(&str.Select).Elem(),
		"Split":          reflect.ValueOf(&str.Split).Elem(),
		"Title":          reflect.ValueOf(&str.Title).Elem(),
		"ToLower":        reflect.ValueOf(&str.ToLower).Elem(),
		"ToUpper":        reflect.ValueOf(&str.ToUpper).Elem(),
		"TrimPrefix":     reflect.ValueOf(&str.TrimPrefix).Elem(),
		"TrimSpace":      reflect.ValueOf(&str.TrimSpace).Elem(),
		"TrimSuffix":     reflect.ValueOf(&str.TrimSuffix).Elem(),
		"Uint16":         reflect.ValueOf(&str.Uint16).Elem(),
		"Uint32":         reflect.ValueOf(&str.Uint32).Elem(),
		"Uint64":         reflect.ValueOf(&str.Uint64).Elem(),
		"Uint8":          reflect.ValueOf(&str.Uint8).Elem(),
	}
}
