// Code generated by 'yaegi extract github.com/injoyai/base/maps'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/maps"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/maps/maps"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewBit":  reflect.ValueOf(maps.NewBit),
		"NewSafe": reflect.ValueOf(maps.NewSafe),

		// type definitions
		"Bit": reflect.ValueOf((*maps.Bit)(nil)),

		// interface wrapper definitions
		"_Bit": reflect.ValueOf((*_github_com_injoyai_base_maps_Bit)(nil)),
	}
}

// _github_com_injoyai_base_maps_Bit is an interface wrapper for Bit type
type _github_com_injoyai_base_maps_Bit struct {
	IValue interface{}
	WGet   func(key uint64) bool
	WSet   func(key uint64, value bool) error
}

func (W _github_com_injoyai_base_maps_Bit) Get(key uint64) bool {
	return W.WGet(key)
}
func (W _github_com_injoyai_base_maps_Bit) Set(key uint64, value bool) error {
	return W.WSet(key, value)
}
