// Code generated by 'yaegi extract github.com/injoyai/base/crypt/gzip'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/gzip"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/gzip/gzip"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DecodeGzip": reflect.ValueOf(gzip.DecodeGzip),
		"EncodeGzip": reflect.ValueOf(gzip.EncodeGzip),
	}
}
