// Code generated by 'yaegi extract github.com/injoyai/ios/v2/client/frame'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/client/frame"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/client/frame/frame"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default":   reflect.ValueOf(&frame.Default).Elem(),
		"Prefix":    reflect.ValueOf(&frame.Prefix).Elem(),
		"ReadFrom":  reflect.ValueOf(frame.ReadFrom),
		"WriteWith": reflect.ValueOf(frame.WriteWith),

		// type definitions
		"Frame": reflect.ValueOf((*frame.Frame)(nil)),
	}
}
