// Code generated by 'yaegi extract github.com/injoyai/base/crypt/crc'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/crypt/crc"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/crypt/crc/crc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CRC16_ARC":         reflect.ValueOf(&crc.CRC16_ARC).Elem(),
		"CRC16_AUG_CCITT":   reflect.ValueOf(&crc.CRC16_AUG_CCITT).Elem(),
		"CRC16_BUYPASS":     reflect.ValueOf(&crc.CRC16_BUYPASS).Elem(),
		"CRC16_CCITT_FALSE": reflect.ValueOf(&crc.CRC16_CCITT_FALSE).Elem(),
		"CRC16_CDMA2000":    reflect.ValueOf(&crc.CRC16_CDMA2000).Elem(),
		"CRC16_CRC_A":       reflect.ValueOf(&crc.CRC16_CRC_A).Elem(),
		"CRC16_DDS_110":     reflect.ValueOf(&crc.CRC16_DDS_110).Elem(),
		"CRC16_DECT_R":      reflect.ValueOf(&crc.CRC16_DECT_R).Elem(),
		"CRC16_DECT_X":      reflect.ValueOf(&crc.CRC16_DECT_X).Elem(),
		"CRC16_DNP":         reflect.ValueOf(&crc.CRC16_DNP).Elem(),
		"CRC16_EN_13757":    reflect.ValueOf(&crc.CRC16_EN_13757).Elem(),
		"CRC16_GENIBUS":     reflect.ValueOf(&crc.CRC16_GENIBUS).Elem(),
		"CRC16_KERMIT":      reflect.ValueOf(&crc.CRC16_KERMIT).Elem(),
		"CRC16_MAXIM":       reflect.ValueOf(&crc.CRC16_MAXIM).Elem(),
		"CRC16_MCRF4XX":     reflect.ValueOf(&crc.CRC16_MCRF4XX).Elem(),
		"CRC16_MODBUS":      reflect.ValueOf(&crc.CRC16_MODBUS).Elem(),
		"CRC16_RIELLO":      reflect.ValueOf(&crc.CRC16_RIELLO).Elem(),
		"CRC16_T10_DIF":     reflect.ValueOf(&crc.CRC16_T10_DIF).Elem(),
		"CRC16_TELEDISK":    reflect.ValueOf(&crc.CRC16_TELEDISK).Elem(),
		"CRC16_TMS37157":    reflect.ValueOf(&crc.CRC16_TMS37157).Elem(),
		"CRC16_USB":         reflect.ValueOf(&crc.CRC16_USB).Elem(),
		"CRC16_XMODEM":      reflect.ValueOf(&crc.CRC16_XMODEM).Elem(),
		"CRC16_X_25":        reflect.ValueOf(&crc.CRC16_X_25).Elem(),
		"CRC8":              reflect.ValueOf(&crc.CRC8).Elem(),
		"CRC8_CDMA2000":     reflect.ValueOf(&crc.CRC8_CDMA2000).Elem(),
		"CRC8_DARC":         reflect.ValueOf(&crc.CRC8_DARC).Elem(),
		"CRC8_DVB_S2":       reflect.ValueOf(&crc.CRC8_DVB_S2).Elem(),
		"CRC8_EBU":          reflect.ValueOf(&crc.CRC8_EBU).Elem(),
		"CRC8_ITU":          reflect.ValueOf(&crc.CRC8_ITU).Elem(),
		"CRC8_I_CODE":       reflect.ValueOf(&crc.CRC8_I_CODE).Elem(),
		"CRC8_MAXIM":        reflect.ValueOf(&crc.CRC8_MAXIM).Elem(),
		"CRC8_ROHC":         reflect.ValueOf(&crc.CRC8_ROHC).Elem(),
		"CRC8_WCDMA":        reflect.ValueOf(&crc.CRC8_WCDMA).Elem(),
		"Checksum16":        reflect.ValueOf(crc.Checksum16),
		"Checksum8":         reflect.ValueOf(crc.Checksum8),
		"Complete16":        reflect.ValueOf(crc.Complete16),
		"Complete8":         reflect.ValueOf(crc.Complete8),
		"Encrypt16":         reflect.ValueOf(crc.Encrypt16),
		"Encrypt16Base64":   reflect.ValueOf(crc.Encrypt16Base64),
		"Encrypt16HEX":      reflect.ValueOf(crc.Encrypt16HEX),
		"Encrypt16String":   reflect.ValueOf(crc.Encrypt16String),
		"Encrypt8":          reflect.ValueOf(crc.Encrypt8),
		"Init16":            reflect.ValueOf(crc.Init16),
		"Init8":             reflect.ValueOf(crc.Init8),
		"MakeTable16":       reflect.ValueOf(crc.MakeTable16),
		"MakeTable8":        reflect.ValueOf(crc.MakeTable8),
		"Update16":          reflect.ValueOf(crc.Update16),
		"Update8":           reflect.ValueOf(crc.Update8),

		// type definitions
		"Param16": reflect.ValueOf((*crc.Param16)(nil)),
		"Param8":  reflect.ValueOf((*crc.Param8)(nil)),
		"Table16": reflect.ValueOf((*crc.Table16)(nil)),
		"Table8":  reflect.ValueOf((*crc.Table8)(nil)),
	}
}
