// Code generated by 'yaegi extract github.com/injoyai/bar'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/bar"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/bar/bar"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Animations":             reflect.ValueOf(&bar.Animations).Elem(),
		"Copy":                   reflect.ValueOf(bar.Copy),
		"DefaultPadding":         reflect.ValueOf(constant.MakeFromLiteral("\" \"", token.STRING, 0)),
		"DefaultStyle":           reflect.ValueOf(constant.MakeFromLiteral("\"#\"", token.STRING, 0)),
		"Download":               reflect.ValueOf(bar.Download),
		"DownloadHLS":            reflect.ValueOf(bar.DownloadHLS),
		"New":                    reflect.ValueOf(bar.New),
		"NewCoroutine":           reflect.ValueOf(bar.NewCoroutine),
		"NewPlan":                reflect.ValueOf(bar.NewPlan),
		"Stat":                   reflect.ValueOf(bar.Stat),
		"WithAnimation":          reflect.ValueOf(bar.WithAnimation),
		"WithAnimationMoon":      reflect.ValueOf(bar.WithAnimationMoon),
		"WithAnimationSnake":     reflect.ValueOf(bar.WithAnimationSnake),
		"WithAutoFlush":          reflect.ValueOf(bar.WithAutoFlush),
		"WithCurrent":            reflect.ValueOf(bar.WithCurrent),
		"WithCustomRateSizeUnit": reflect.ValueOf(bar.WithCustomRateSizeUnit),
		"WithCustomSize":         reflect.ValueOf(bar.WithCustomSize),
		"WithDate":               reflect.ValueOf(bar.WithDate),
		"WithDateTime":           reflect.ValueOf(bar.WithDateTime),
		"WithFinal":              reflect.ValueOf(bar.WithFinal),
		"WithFinalLn":            reflect.ValueOf(bar.WithFinalLn),
		"WithFlush":              reflect.ValueOf(bar.WithFlush),
		"WithFormat":             reflect.ValueOf(bar.WithFormat),
		"WithFormatDefault":      reflect.ValueOf(bar.WithFormatDefault),
		"WithFormatDefaultUnit":  reflect.ValueOf(bar.WithFormatDefaultUnit),
		"WithFormatSplit":        reflect.ValueOf(bar.WithFormatSplit),
		"WithHLSCoroutine":       reflect.ValueOf(bar.WithHLSCoroutine),
		"WithHLSProxy":           reflect.ValueOf(bar.WithHLSProxy),
		"WithHLSRetry":           reflect.ValueOf(bar.WithHLSRetry),
		"WithHLSShowDetails":     reflect.ValueOf(bar.WithHLSShowDetails),
		"WithIntervalFlush":      reflect.ValueOf(bar.WithIntervalFlush),
		"WithOption":             reflect.ValueOf(bar.WithOption),
		"WithPlan":               reflect.ValueOf(bar.WithPlan),
		"WithPrefix":             reflect.ValueOf(bar.WithPrefix),
		"WithRate":               reflect.ValueOf(bar.WithRate),
		"WithRateSize":           reflect.ValueOf(bar.WithRateSize),
		"WithRateSizeUnit":       reflect.ValueOf(bar.WithRateSizeUnit),
		"WithRemain":             reflect.ValueOf(bar.WithRemain),
		"WithRemainInterval":     reflect.ValueOf(bar.WithRemainInterval),
		"WithSpeed":              reflect.ValueOf(bar.WithSpeed),
		"WithSpeedAvg":           reflect.ValueOf(bar.WithSpeedAvg),
		"WithSpeedUnit":          reflect.ValueOf(bar.WithSpeedUnit),
		"WithSpeedUnitAvg":       reflect.ValueOf(bar.WithSpeedUnitAvg),
		"WithSuffix":             reflect.ValueOf(bar.WithSuffix),
		"WithText":               reflect.ValueOf(bar.WithText),
		"WithTime":               reflect.ValueOf(bar.WithTime),
		"WithTotal":              reflect.ValueOf(bar.WithTotal),
		"WithUsed":               reflect.ValueOf(bar.WithUsed),
		"WithUsedSecond":         reflect.ValueOf(bar.WithUsedSecond),
		"WithWriter":             reflect.ValueOf(bar.WithWriter),

		// type definitions
		"Bar":               reflect.ValueOf((*bar.Bar)(nil)),
		"Coroutine":         reflect.ValueOf((*bar.Coroutine)(nil)),
		"DownloadHLSConfig": reflect.ValueOf((*bar.DownloadHLSConfig)(nil)),
		"Format":            reflect.ValueOf((*bar.Format)(nil)),
		"HLSOption":         reflect.ValueOf((*bar.HLSOption)(nil)),
		"Option":            reflect.ValueOf((*bar.Option)(nil)),
		"Plan":              reflect.ValueOf((*bar.Plan)(nil)),
		"PlanOption":        reflect.ValueOf((*bar.PlanOption)(nil)),
		"Reader":            reflect.ValueOf((*bar.Reader)(nil)),
	}
}
