// Code generated by 'yaegi extract github.com/injoyai/conv/codec/yaml'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec/yaml"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/yaml/yaml"] = map[string]reflect.Value{
		// type definitions
		"Yaml": reflect.ValueOf((*yaml.Yaml)(nil)),
	}
}
