// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/serial'. DO NOT EDIT.

package lib

import (
	_ "github.com/goburrow/serial"
	"github.com/injoyai/ios/v2/module/serial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/serial/serial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":    reflect.ValueOf(serial.Dial),
		"NewDial": reflect.ValueOf(serial.NewDial),
		"Open":    reflect.ValueOf(serial.Open),

		// type definitions
		"Client":      reflect.ValueOf((*serial.Client)(nil)),
		"Config":      reflect.ValueOf((*serial.Config)(nil)),
		"RS485Config": reflect.ValueOf((*serial.RS485Config)(nil)),

		// interface wrapper definitions
		"_Client": reflect.ValueOf((*_github_com_injoyai_ios_v2_module_serial_Client)(nil)),
	}
}

// _github_com_injoyai_ios_v2_module_serial_Client is an interface wrapper for Client type
type _github_com_injoyai_ios_v2_module_serial_Client struct {
	IValue interface{}
	WClose func() error
	WOpen  func(a0 *serial.Config) error
	WRead  func(p []byte) (n int, err error)
	WWrite func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_v2_module_serial_Client) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_v2_module_serial_Client) Open(a0 *serial.Config) error {
	return W.WOpen(a0)
}
func (W _github_com_injoyai_ios_v2_module_serial_Client) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_v2_module_serial_Client) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
