// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/udp'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/udp"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/udp/udp"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewDial": reflect.ValueOf(udp.NewDial),

		// type definitions
		"Server": reflect.ValueOf((*udp.Server)(nil)),
	}
}
