// Code generated by 'yaegi extract github.com/injoyai/conv/codec/json'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv/codec/json"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/codec/json/json"] = map[string]reflect.Value{
		// type definitions
		"Json": reflect.ValueOf((*json.Json)(nil)),
	}
}
