// Code generated by 'yaegi extract github.com/injoyai/base/maps/wait'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/maps/wait"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/base/maps/wait/wait"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Async":      reflect.ValueOf(wait.Async),
		"Default":    reflect.ValueOf(&wait.Default).Elem(),
		"Done":       reflect.ValueOf(wait.Done),
		"IsWait":     reflect.ValueOf(wait.IsWait),
		"New":        reflect.ValueOf(wait.New),
		"SetReuse":   reflect.ValueOf(wait.SetReuse),
		"SetTimeout": reflect.ValueOf(wait.SetTimeout),
		"Sync":       reflect.ValueOf(wait.Sync),
		"Wait":       reflect.ValueOf(wait.Wait),
	}
}
