// Code generated by 'yaegi extract github.com/injoyai/ios/v2/module/common'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/module/common"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/module/common/common"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DealErr":    reflect.ValueOf(common.DealErr),
		"LevelAll":   reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"LevelDebug": reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"LevelError": reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"LevelInfo":  reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"LevelNone":  reflect.ValueOf(constant.MakeFromLiteral("9", token.INT, 0)),
		"NewLogger":  reflect.ValueOf(common.NewLogger),

		// type definitions
		"Logger": reflect.ValueOf((*common.Logger)(nil)),

		// interface wrapper definitions
		"_Logger": reflect.ValueOf((*_github_com_injoyai_ios_v2_module_common_Logger)(nil)),
	}
}

// _github_com_injoyai_ios_v2_module_common_Logger is an interface wrapper for Logger type
type _github_com_injoyai_ios_v2_module_common_Logger struct {
	IValue     interface{}
	WEnable    func(b ...bool)
	WErrorf    func(format string, v ...interface{})
	WInfof     func(format string, v ...interface{})
	WReadln    func(prefix string, p []byte)
	WSetEncode func(f func(p []byte) string)
	WSetLevel  func(level int)
	WWithHEX   func()
	WWithUTF8  func()
	WWriteln   func(prefix string, p []byte)
}

func (W _github_com_injoyai_ios_v2_module_common_Logger) Enable(b ...bool) {
	W.WEnable(b...)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) Errorf(format string, v ...interface{}) {
	W.WErrorf(format, v...)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) Infof(format string, v ...interface{}) {
	W.WInfof(format, v...)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) Readln(prefix string, p []byte) {
	W.WReadln(prefix, p)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) SetEncode(f func(p []byte) string) {
	W.WSetEncode(f)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) SetLevel(level int) {
	W.WSetLevel(level)
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) WithHEX() {
	W.WWithHEX()
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) WithUTF8() {
	W.WWithUTF8()
}
func (W _github_com_injoyai_ios_v2_module_common_Logger) Writeln(prefix string, p []byte) {
	W.WWriteln(prefix, p)
}
