// Code generated by 'yaegi extract github.com/injoyai/ios/v2/server'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/v2/server"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/v2/server/server"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":                 reflect.ValueOf(server.New),
		"Run":                 reflect.ValueOf(server.Run),
		"RunContext":          reflect.ValueOf(server.RunContext),
		"WithClientConnected": reflect.ValueOf(server.WithClientConnected),
		"WithClientOptions":   reflect.ValueOf(server.WithClientOptions),
		"WithLoggerDisable":   reflect.ValueOf(server.WithLoggerDisable),
		"WithLoggerEnable":    reflect.ValueOf(server.WithLoggerEnable),
		"WithLoggerLevel":     reflect.ValueOf(server.WithLoggerLevel),

		// type definitions
		"Event":  reflect.ValueOf((*server.Event)(nil)),
		"Option": reflect.ValueOf((*server.Option)(nil)),
		"Server": reflect.ValueOf((*server.Server)(nil)),
	}
}
