// Code generated by 'yaegi extract github.com/injoyai/frame/gins'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/frame/gins"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/frame/gins/gins"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindCode":    reflect.ValueOf(gins.BindCode),
		"BindHtml":    reflect.ValueOf(gins.BindHtml),
		"Default":     reflect.ValueOf(gins.Default),
		"New":         reflect.ValueOf(gins.New),
		"WithCORS":    reflect.ValueOf(gins.WithCORS),
		"WithDefault": reflect.ValueOf(gins.WithDefault),
		"WithLog":     reflect.ValueOf(gins.WithLog),
		"WithOption":  reflect.ValueOf(gins.WithOption),
		"WithPing":    reflect.ValueOf(gins.WithPing),
		"WithPort":    reflect.ValueOf(gins.WithPort),
		"WithRecover": reflect.ValueOf(gins.WithRecover),
		"WithSwagger": reflect.ValueOf(gins.WithSwagger),

		// type definitions
		"Ctx":     reflect.ValueOf((*gins.Ctx)(nil)),
		"Grouper": reflect.ValueOf((*gins.Grouper)(nil)),
		"Handler": reflect.ValueOf((*gins.Handler)(nil)),
		"Option":  reflect.ValueOf((*gins.Option)(nil)),
		"Server":  reflect.ValueOf((*gins.Server)(nil)),
	}
}
