// Code generated by 'yaegi extract github.com/injoyai/conv'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/conv"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/conv/conv"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Array":         reflect.ValueOf(conv.Array),
		"BIN":           reflect.ValueOf(conv.BIN),
		"BINBool":       reflect.ValueOf(conv.BINBool),
		"BINStr":        reflect.ValueOf(conv.BINStr),
		"Bool":          reflect.ValueOf(conv.Bool),
		"Byte":          reflect.ValueOf(conv.Byte),
		"Bytes":         reflect.ValueOf(conv.Bytes),
		"BytesZ":        reflect.ValueOf(conv.BytesZ),
		"Copy":          reflect.ValueOf(conv.Copy),
		"DMap":          reflect.ValueOf(conv.DMap),
		"Duration":      reflect.ValueOf(conv.Duration),
		"Float32":       reflect.ValueOf(conv.Float32),
		"Float64":       reflect.ValueOf(conv.Float64),
		"GMap":          reflect.ValueOf(conv.GMap),
		"GetNature":     reflect.ValueOf(conv.GetNature),
		"GetNatureKind": reflect.ValueOf(conv.GetNatureKind),
		"HEX":           reflect.ValueOf(conv.HEX),
		"HEXStr":        reflect.ValueOf(conv.HEXStr),
		"IMap":          reflect.ValueOf(conv.IMap),
		"Int":           reflect.ValueOf(conv.Int),
		"Int16":         reflect.ValueOf(conv.Int16),
		"Int32":         reflect.ValueOf(conv.Int32),
		"Int64":         reflect.ValueOf(conv.Int64),
		"Int64s":        reflect.ValueOf(conv.Int64s),
		"Int8":          reflect.ValueOf(conv.Int8),
		"IntSize":       reflect.ValueOf(constant.MakeFromLiteral("64", token.INT, 0)),
		"Interfaces":    reflect.ValueOf(conv.Interfaces),
		"Ints":          reflect.ValueOf(conv.Ints),
		"IsArray":       reflect.ValueOf(conv.IsArray),
		"IsBool":        reflect.ValueOf(conv.IsBool),
		"IsDefault":     reflect.ValueOf(conv.IsDefault),
		"IsFloat":       reflect.ValueOf(conv.IsFloat),
		"IsInt":         reflect.ValueOf(conv.IsInt),
		"IsNil":         reflect.ValueOf(conv.IsNil),
		"IsNumber":      reflect.ValueOf(conv.IsNumber),
		"IsPointer":     reflect.ValueOf(conv.IsPointer),
		"IsString":      reflect.ValueOf(conv.IsString),
		"IsTime":        reflect.ValueOf(conv.IsTime),
		"IsZero":        reflect.ValueOf(conv.IsZero),
		"New":           reflect.ValueOf(conv.New),
		"NewExtend":     reflect.ValueOf(conv.NewExtend),
		"NewMap":        reflect.ValueOf(conv.NewMap),
		"Nil":           reflect.ValueOf(conv.Nil),
		"OCT":           reflect.ValueOf(conv.OCT),
		"OCTStr":        reflect.ValueOf(conv.OCTStr),
		"Rune":          reflect.ValueOf(conv.Rune),
		"Runes":         reflect.ValueOf(conv.Runes),
		"SMap":          reflect.ValueOf(conv.SMap),
		"String":        reflect.ValueOf(conv.String),
		"Strings":       reflect.ValueOf(conv.Strings),
		"Uint":          reflect.ValueOf(conv.Uint),
		"Uint16":        reflect.ValueOf(conv.Uint16),
		"Uint32":        reflect.ValueOf(conv.Uint32),
		"Uint64":        reflect.ValueOf(conv.Uint64),
		"Uint8":         reflect.ValueOf(conv.Uint8),
		"Unmarshal":     reflect.ValueOf(conv.Unmarshal),

		// type definitions
		"Bytes2":         reflect.ValueOf((*conv.Bytes2)(nil)),
		"Map":            reflect.ValueOf((*conv.Map)(nil)),
		"UnmarshalParam": reflect.ValueOf((*conv.UnmarshalParam)(nil)),
		"Var":            reflect.ValueOf((*conv.Var)(nil)),
	}
}
